// ============================================================
// CHINA PRIME DMC — Content Data
// Operated by: Youyouhui Travel Services Co., Ltd.
// ============================================================

export const WHATSAPP_NUMBER = "+447985052302";
export const WHATSAPP_URL = `https://wa.me/${WHATSAPP_NUMBER.replace(/\D/g, "")}`;
export const EMAIL = "Chinaprimedmc@gmail.com";

export interface Destination {
  id: string;
  name: string;
  category: "iconic" | "cultural" | "adventure" | "luxury";
  tagline: string;
  description: string;
  image: string;
  highlights: string[];
  bestTime: string;
  duration: string;
}

export interface Journey {
  id: string;
  title: string;
  subtitle: string;
  duration: string;
  destinations: string[];
  difficulty: "Easy" | "Moderate" | "Challenging";
  image: string;
  category: "Iconic" | "Cultural" | "Adventure" | "Culinary" | "Wellness";
  tags?: ("Family-Friendly" | "Halal" | "Women-Only" | "Senior-Friendly" | "Accessible" | "Vegetarian")[];
  highlights: string[];
  overview: string;
  days: { day: string; title: string; description: string }[];
  accommodations: string[];
  experiences: string[];
  expertNotes: string;
  faqs: { q: string; a: string }[];
}

export interface BlogPost {
  id: string;
  title: string;
  category: string;
  excerpt: string;
  readTime: string;
  image: string;
  content: string;
  tags: string[];
}

export const destinations: Destination[] = [
  // ICONIC CHINA
  {
    id: "beijing",
    name: "Beijing",
    category: "iconic",
    tagline: "Where imperial grandeur meets modern ambition",
    description: "China's ancient capital holds five millennia of history within its ring roads. From the Forbidden City's ochre walls to the Great Wall's mountain spine, Beijing rewards those who look beyond the obvious.",
    image: "https://images.unsplash.com/photo-1508804185872-d7badad00f7d?w=800&q=80",
    highlights: ["Forbidden City private access", "Great Wall at dawn", "Hutong alley exploration", "798 Art District", "Temple of Heaven"],
    bestTime: "April–May, September–October",
    duration: "3–5 days",
  },
  {
    id: "shanghai",
    name: "Shanghai",
    category: "iconic",
    tagline: "The city that never stopped reinventing itself",
    description: "Shanghai is China's most cosmopolitan city — a place where Art Deco Bund architecture faces a forest of futurist towers across the Huangpu River. Its energy is unlike anywhere else on earth.",
    image: "https://images.unsplash.com/photo-1474181487882-5abf3f0ba6c2?w=800&q=80",
    highlights: ["Bund at golden hour", "French Concession streets", "Xintiandi dining", "M50 art galleries", "Yu Garden"],
    bestTime: "March–May, September–November",
    duration: "3–4 days",
  },
  {
    id: "xian",
    name: "Xi'an",
    category: "iconic",
    tagline: "The city where the Silk Road began",
    description: "Xi'an was once the greatest city on earth — capital of the Tang Dynasty, eastern terminus of the Silk Road. The Terracotta Army alone justifies the journey, but the ancient city walls and Muslim Quarter reveal a city still very much alive.",
    image: "https://images.unsplash.com/photo-1547981609-4b6bfe67ca0b?w=800&q=80",
    highlights: ["Terracotta Army private tour", "City wall cycling at dawn", "Muslim Quarter food walk", "Big Wild Goose Pagoda", "Shaanxi History Museum"],
    bestTime: "April–June, September–November",
    duration: "2–3 days",
  },
  {
    id: "guilin",
    name: "Guilin",
    category: "iconic",
    tagline: "The landscape painters have been trying to capture for centuries",
    description: "The karst peaks of Guilin and Yangshuo are so otherworldly they appear in Chinese ink paintings as idealized landscapes. The reality is even more extraordinary — mist-wrapped limestone towers rising from jade rivers.",
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663786910793/nv3b3r8xSigzoBGpUx4ZRH/hero-bg-kmefs8MDDAygocYYphq93g.webp",
    highlights: ["Li River private cruise", "Yangshuo countryside cycling", "Reed Flute Cave", "Longji Rice Terraces", "Cormorant fishing at dusk"],
    bestTime: "April–October",
    duration: "3–4 days",
  },
  {
    id: "chengdu",
    name: "Chengdu",
    category: "iconic",
    tagline: "The city that mastered the art of living well",
    description: "Chengdu moves at its own pace — unhurried, pleasure-seeking, deeply cultured. Home to giant pandas, fiery Sichuan cuisine, and a teahouse culture that has survived dynasties, it is China's most livable city.",
    image: "https://images.unsplash.com/photo-1548919973-5cef591cdbc9?w=800&q=80",
    highlights: ["Giant Panda Base", "Sichuan cooking class", "Jinli Ancient Street", "Leshan Giant Buddha", "Qingchengshan Mountain"],
    bestTime: "March–June, September–November",
    duration: "2–4 days",
  },
  {
    id: "hong-kong",
    name: "Hong Kong",
    category: "iconic",
    tagline: "Where East meets West at the edge of the sea",
    description: "Hong Kong is a city of extraordinary contrasts — gleaming towers above ancient temples, Michelin stars beside street stalls, colonial heritage within a Chinese soul. An essential gateway to understanding modern China.",
    image: "https://images.unsplash.com/photo-1536599018102-9f803c140fc1?w=800&q=80",
    highlights: ["Victoria Peak at night", "Dim sum in Kowloon", "Lantau Island temples", "Star Ferry crossing", "PMQ design district"],
    bestTime: "October–April",
    duration: "2–3 days",
  },
  {
    id: "suzhou",
    name: "Suzhou",
    category: "iconic",
    tagline: "Heaven on earth, as the ancient saying goes",
    description: "Suzhou's classical gardens are UNESCO-listed masterpieces of landscape design — miniature worlds where rocks, water, and pavilions create meditative environments of extraordinary beauty. The city's silk industry and canal network complete the picture.",
    image: "https://images.unsplash.com/photo-1547981609-4b6bfe67ca0b?w=800&q=80",
    highlights: ["Humble Administrator's Garden", "Master of Nets Garden by night", "Grand Canal boat ride", "Silk Museum", "Pingjiang Road"],
    bestTime: "April–May, September–October",
    duration: "1–2 days",
  },
  {
    id: "hangzhou",
    name: "Hangzhou",
    category: "iconic",
    tagline: "The lake that inspired a thousand poets",
    description: "West Lake has been celebrated in Chinese poetry for over a thousand years. Marco Polo called Hangzhou the finest city in the world. Today, it remains one of China's most beautiful destinations — a city where nature and culture exist in perfect balance.",
    image: "https://images.unsplash.com/photo-1508804185872-d7badad00f7d?w=800&q=80",
    highlights: ["West Lake sunrise boat", "Longjing tea plantation", "Lingyin Temple", "Song Dynasty Town", "Xixi Wetlands"],
    bestTime: "March–May, September–November",
    duration: "2–3 days",
  },
  // CULTURAL CHINA
  {
    id: "yunnan",
    name: "Yunnan",
    category: "cultural",
    tagline: "Where China's diversity reaches its most vivid expression",
    description: "Yunnan is China's most ethnically diverse province — home to 26 of China's 56 recognized ethnic groups. From the ancient tea-horse road towns of Lijiang and Dali to the Tibetan highlands of Shangri-La, Yunnan offers journeys of extraordinary cultural depth.",
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663786910793/nv3b3r8xSigzoBGpUx4ZRH/destination-yunnan-MgmXuu6XECuXSfSXdqH7Kn.webp",
    highlights: ["Tiger Leaping Gorge trek", "Lijiang Old Town", "Dali Bai culture", "Shangri-La monastery", "Rice terraces of Yuanyang"],
    bestTime: "March–May, September–November",
    duration: "7–10 days",
  },
  {
    id: "sichuan",
    name: "Sichuan",
    category: "cultural",
    tagline: "Land of abundance, fire, and ancient mystery",
    description: "Sichuan is a province of superlatives — the world's spiciest cuisine, the world's largest Buddha, and some of China's most dramatic mountain scenery. The ancient Shu kingdom left a cultural legacy as rich as any in China.",
    image: "https://images.unsplash.com/photo-1548919973-5cef591cdbc9?w=800&q=80",
    highlights: ["Jiuzhaigou Valley", "Emei Mountain pilgrimage", "Sichuan Opera face-changing", "Sanxingdui Bronze Age site", "Tibetan border communities"],
    bestTime: "April–June, September–October",
    duration: "5–8 days",
  },
  {
    id: "shanxi",
    name: "Shanxi",
    category: "cultural",
    tagline: "China's most underrated treasury of ancient architecture",
    description: "Shanxi contains more ancient wooden architecture than the rest of China combined. The Hanging Monastery defies gravity; the Yungang Grottoes contain 51,000 Buddhist sculptures; the ancient walled city of Pingyao is perfectly preserved.",
    image: "https://images.unsplash.com/photo-1508804185872-d7badad00f7d?w=800&q=80",
    highlights: ["Pingyao Ancient City", "Yungang Grottoes", "Hanging Monastery", "Wang Family Compound", "Wutai Mountain"],
    bestTime: "April–October",
    duration: "4–6 days",
  },
  {
    id: "henan",
    name: "Henan",
    category: "cultural",
    tagline: "The cradle of Chinese civilization",
    description: "Henan is where Chinese civilization was born. The ancient capitals of Luoyang and Kaifeng, the Shaolin Temple birthplace of kung fu, and the Longmen Grottoes' 100,000 Buddhist carvings make this one of China's most historically significant provinces.",
    image: "https://images.unsplash.com/photo-1547981609-4b6bfe67ca0b?w=800&q=80",
    highlights: ["Shaolin Temple kung fu", "Longmen Grottoes", "Luoyang peonies in bloom", "Kaifeng Song Dynasty culture", "Yuntai Mountain"],
    bestTime: "April–May, September–October",
    duration: "4–5 days",
  },
  {
    id: "fujian",
    name: "Fujian",
    category: "cultural",
    tagline: "Earth towers, tea mountains, and the sea",
    description: "Fujian's Hakka tulou — massive circular earthen fortresses housing entire communities — are among China's most extraordinary architectural achievements. The province's tea culture, coastal scenery, and Gulangyu Island complete a uniquely rewarding journey.",
    image: "https://images.unsplash.com/photo-1474181487882-5abf3f0ba6c2?w=800&q=80",
    highlights: ["Hakka Tulou cluster", "Wuyi Mountain tea culture", "Gulangyu Island", "Xiamen colonial architecture", "Fujian seafood"],
    bestTime: "March–May, September–November",
    duration: "4–6 days",
  },
  {
    id: "anhui",
    name: "Anhui",
    category: "cultural",
    tagline: "Where ink-wash paintings come to life",
    description: "The ancient villages of Hongcun and Xidi look exactly like Chinese ink paintings — whitewashed walls, black tile roofs, and moon ponds reflecting the sky. Huangshan (Yellow Mountain) above the clouds completes one of China's most visually extraordinary journeys.",
    image: "https://images.unsplash.com/photo-1508804185872-d7badad00f7d?w=800&q=80",
    highlights: ["Huangshan at sunrise", "Hongcun village", "Xidi village", "Bixi ancient road", "Hui-style cuisine"],
    bestTime: "March–May, September–November",
    duration: "3–5 days",
  },
  {
    id: "guangdong",
    name: "Guangdong",
    category: "cultural",
    tagline: "The province that feeds the world",
    description: "Guangdong is the origin of Cantonese cuisine — arguably the world's greatest food culture. Beyond the food, the province offers Lingnan architecture, ancestral halls of extraordinary beauty, and the Pearl River Delta's fascinating modern story.",
    image: "https://images.unsplash.com/photo-1536599018102-9f803c140fc1?w=800&q=80",
    highlights: ["Dim sum culture deep dive", "Kaiping Diaolou towers", "Foshan ancestral temple", "Guangzhou food tour", "Chaozhou old city"],
    bestTime: "October–April",
    duration: "3–5 days",
  },
  // ADVENTURE CHINA
  {
    id: "zhangjiajie",
    name: "Zhangjiajie",
    category: "adventure",
    tagline: "The landscape that inspired Avatar's floating mountains",
    description: "Zhangjiajie's sandstone pillars rise vertically from the forest floor to heights of over 200 meters — a landscape so alien it inspired the floating Hallelujah Mountains in Avatar. Walking among them feels like entering another world.",
    image: "https://images.unsplash.com/photo-1548919973-5cef591cdbc9?w=800&q=80",
    highlights: ["Avatar Hallelujah Mountain", "Tianmen Mountain glass bridge", "Zhangjiajie Grand Canyon", "Tujia ethnic village", "Bailong Elevator"],
    bestTime: "April–October",
    duration: "3–4 days",
  },
  {
    id: "tibet",
    name: "Tibet",
    category: "adventure",
    tagline: "The roof of the world, where sky and earth meet",
    description: "Tibet is the world's highest plateau — a land of extraordinary spiritual intensity, vast empty landscapes, and one of the world's great living cultures. The Potala Palace, Jokhang Temple, and the road to Mount Everest Base Camp are among humanity's most profound travel experiences.",
    image: "https://images.unsplash.com/photo-1508804185872-d7badad00f7d?w=800&q=80",
    highlights: ["Potala Palace", "Jokhang Temple kora", "Namtso Lake", "Everest Base Camp", "Sera Monastery debate"],
    bestTime: "April–October",
    duration: "7–10 days",
  },
  {
    id: "xinjiang",
    name: "Xinjiang",
    category: "adventure",
    tagline: "The Silk Road's greatest stage",
    description: "Xinjiang is China's largest province — a vast landscape of desert, mountain, and oasis that was the heart of the ancient Silk Road. Kashgar's Sunday bazaar, the Karakorum Highway, and the Flaming Mountains offer journeys of epic scale.",
    image: "https://images.unsplash.com/photo-1474181487882-5abf3f0ba6c2?w=800&q=80",
    highlights: ["Kashgar old city", "Karakorum Highway", "Heavenly Lake", "Flaming Mountains", "Uyghur cuisine"],
    bestTime: "May–October",
    duration: "7–10 days",
  },
  {
    id: "qinghai",
    name: "Qinghai",
    category: "adventure",
    tagline: "The source of Asia's great rivers",
    description: "Qinghai is where the Yellow River, Yangtze, and Mekong all begin — a high-altitude plateau of extraordinary natural beauty and Tibetan Buddhist culture. Qinghai Lake, the largest lake in China, and the Kumbum Monastery are highlights of a deeply rewarding journey.",
    image: "https://images.unsplash.com/photo-1548919973-5cef591cdbc9?w=800&q=80",
    highlights: ["Qinghai Lake", "Kumbum Monastery", "Sanjiangyuan National Park", "Tibetan nomad communities", "Qinghai-Tibet Railway"],
    bestTime: "June–September",
    duration: "5–7 days",
  },
  {
    id: "gansu",
    name: "Gansu",
    category: "adventure",
    tagline: "The corridor where China met the world",
    description: "Gansu's Hexi Corridor was the narrow passage through which the Silk Road connected China to Central Asia. The Mogao Caves at Dunhuang contain the world's greatest collection of Buddhist art; the Zhangye Danxia Landform is a geological masterpiece of color.",
    image: "https://images.unsplash.com/photo-1508804185872-d7badad00f7d?w=800&q=80",
    highlights: ["Mogao Caves at Dunhuang", "Zhangye Rainbow Mountains", "Jiayuguan Fort", "Labrang Monastery", "Crescent Moon Lake"],
    bestTime: "May–October",
    duration: "6–8 days",
  },
  {
    id: "inner-mongolia",
    name: "Inner Mongolia",
    category: "adventure",
    tagline: "Where the grasslands stretch to the horizon",
    description: "Inner Mongolia's vast grasslands offer a profound experience of space and silence. Staying in a traditional ger, riding horses at dawn, and watching the Milky Way from the steppe are experiences that reset the soul.",
    image: "https://images.unsplash.com/photo-1474181487882-5abf3f0ba6c2?w=800&q=80",
    highlights: ["Hulunbuir grasslands", "Horseback riding", "Mongolian ger stay", "Resonant Sand Gorge", "Genghis Khan Mausoleum"],
    bestTime: "June–September",
    duration: "4–6 days",
  },
  {
    id: "guizhou",
    name: "Guizhou",
    category: "adventure",
    tagline: "China's last frontier of authentic minority culture",
    description: "Guizhou is China's most ethnically diverse and least visited province — a place where Miao and Dong minority cultures survive in extraordinary vitality. Wooden drum towers, silver jewelry festivals, and the world's largest radio telescope make this a journey unlike any other.",
    image: "https://images.unsplash.com/photo-1548919973-5cef591cdbc9?w=800&q=80",
    highlights: ["Miao silver festival", "Dong wind-and-rain bridges", "Huangguoshu Waterfall", "FAST telescope", "Zhenyuan ancient town"],
    bestTime: "April–October",
    duration: "5–7 days",
  },
  // LUXURY / URBAN CHINA
  {
    id: "shenzhen",
    name: "Shenzhen",
    category: "luxury",
    tagline: "The city that built itself in 40 years",
    description: "Shenzhen is the world's most remarkable urban story — a fishing village transformed into a global technology capital in four decades. Its design culture, contemporary art scene, and innovation ecosystem make it essential for understanding China's future.",
    image: "https://images.unsplash.com/photo-1536599018102-9f803c140fc1?w=800&q=80",
    highlights: ["OCT-LOFT creative district", "Design Society museum", "Dafen Oil Painting Village", "Shenzhen Bay Park", "Huaqiangbei electronics market"],
    bestTime: "October–April",
    duration: "2–3 days",
  },
  {
    id: "macau",
    name: "Macau",
    category: "luxury",
    tagline: "Where Portuguese baroque meets Chinese tradition",
    description: "Macau is the world's most densely packed UNESCO World Heritage site — a labyrinth of Portuguese colonial churches, Chinese temples, and Art Deco casinos. Its culinary culture, a unique fusion of Portuguese and Cantonese traditions, is among Asia's most distinctive.",
    image: "https://images.unsplash.com/photo-1474181487882-5abf3f0ba6c2?w=800&q=80",
    highlights: ["Ruins of St. Paul's", "Senado Square", "Cotai luxury resorts", "Macanese cuisine", "A-Ma Temple"],
    bestTime: "October–April",
    duration: "1–2 days",
  },
  {
    id: "nanjing",
    name: "Nanjing",
    category: "luxury",
    tagline: "The southern capital that shaped Chinese history",
    description: "Nanjing was China's capital for six dynasties and the Republic of China. Its ancient city walls, the Sun Yat-sen Mausoleum, and the Confucius Temple district tell a story of extraordinary historical depth. The Qinhuai River at night is one of China's most romantic scenes.",
    image: "https://images.unsplash.com/photo-1508804185872-d7badad00f7d?w=800&q=80",
    highlights: ["Ming city walls", "Sun Yat-sen Mausoleum", "Qinhuai River night cruise", "Nanjing Museum", "Purple Mountain"],
    bestTime: "March–May, September–November",
    duration: "2–3 days",
  },
  {
    id: "wuhan",
    name: "Wuhan",
    category: "luxury",
    tagline: "The city at the heart of China",
    description: "Wuhan sits at the confluence of the Yangtze and Han Rivers — China's geographic and cultural crossroads. Yellow Crane Tower, East Lake (China's largest urban lake), and a food culture built around hot dry noodles make it a city of genuine character.",
    image: "https://images.unsplash.com/photo-1548919973-5cef591cdbc9?w=800&q=80",
    highlights: ["Yellow Crane Tower", "East Lake cycling", "Wuhan hot dry noodles", "Hubei Provincial Museum", "Yangtze River crossing"],
    bestTime: "March–May, September–October",
    duration: "2–3 days",
  },
  {
    id: "chongqing",
    name: "Chongqing",
    category: "luxury",
    tagline: "The mountain city that defies gravity",
    description: "Chongqing is built on mountains at the confluence of two great rivers — a vertical city of cable cars, elevated walkways, and dramatic night views. Its hotpot culture is the most intense in China; the Yangtze River cruise to the Three Gorges is one of the world's great river journeys.",
    image: "https://images.unsplash.com/photo-1536599018102-9f803c140fc1?w=800&q=80",
    highlights: ["Yangtze River cruise", "Chongqing hotpot experience", "Ciqikou ancient town", "Three Gorges", "Hongya Cave at night"],
    bestTime: "March–May, September–November",
    duration: "3–4 days",
  },
];

export const journeys: Journey[] = [
  {
    id: "imperial-heartland",
    title: "The Imperial Heartland",
    subtitle: "Beijing · Xi'an · Luoyang",
    duration: "12 days",
    destinations: ["beijing", "xian", "henan"],
    difficulty: "Easy",
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663786910793/nv3b3r8xSigzoBGpUx4ZRH/hero-bg-2-GoNbVjS2NTZPw3Hq8K79y4.webp",
    category: "Iconic",
    highlights: ["Private Great Wall sunrise", "Terracotta Army after hours", "Shaolin kung fu master", "Longmen Grottoes at dusk"],
    overview: "China's imperial story spans five thousand years and three great capitals. This journey moves through the heart of that story — from Beijing's Forbidden City to Xi'an's Terracotta Army to Luoyang's Buddhist grottoes — with private access and expert guidance that transforms monuments into living history.",
    days: [
      { day: "Day 1", title: "Arrival in Beijing", description: "Private transfer to your hotel. Evening orientation walk through the Hutong alleyways near the Drum Tower." },
      { day: "Day 2", title: "Forbidden City & Tiananmen", description: "Private early-morning access to the Forbidden City before the crowds arrive. Afternoon at the Temple of Heaven." },
      { day: "Day 3", title: "The Great Wall at Dawn", description: "Private driver to Jinshanling section at sunrise. Walk a 10km restored stretch with your expert guide." },
      { day: "Day 4", title: "Beijing's Hidden Layers", description: "798 Art District, Lama Temple, and a Hutong cooking class with a local family." },
      { day: "Day 5", title: "Flight to Xi'an", description: "Morning flight. Afternoon walk along the ancient city walls by bicycle." },
      { day: "Day 6", title: "Terracotta Army", description: "Private guide to the Terracotta Army. After-hours access to Pit 1 when the day visitors have left." },
      { day: "Day 7", title: "Xi'an's Muslim Quarter", description: "Morning at the Big Wild Goose Pagoda. Afternoon food walk through the Muslim Quarter with a culinary guide." },
      { day: "Day 8", title: "Train to Luoyang", description: "High-speed train through the Wei River valley. Afternoon at the Longmen Grottoes." },
      { day: "Day 9", title: "Shaolin Temple", description: "Private visit to Shaolin Temple. Kung fu demonstration with a resident master." },
      { day: "Day 10", title: "Luoyang's Ancient Streets", description: "Luoyang Museum and the Tang Dynasty old town. Luoyang water banquet dinner." },
      { day: "Day 11", title: "Return to Beijing", description: "High-speed train to Beijing. Farewell dinner at a Siheyuan courtyard restaurant." },
      { day: "Day 12", title: "Departure", description: "Private transfer to Beijing Capital International Airport." },
    ],
    accommodations: ["The Peninsula Beijing", "Sofitel Legend People's Grand Hotel Xi'an", "Wanda Realm Luoyang"],
    experiences: ["Private Forbidden City access", "Great Wall sunrise hike", "Terracotta Army after-hours", "Hutong cooking class", "Shaolin kung fu"],
    expertNotes: "The Jinshanling section of the Great Wall is our preferred choice — less visited than Mutianyu, more dramatic than Badaling. Arrive by 6am in spring or autumn for the best light and complete solitude.",
    faqs: [
      { q: "Do I need a visa for China?", a: "Most Western passport holders can now enter China visa-free for up to 15 days. For longer stays, we assist with the visa application process." },
      { q: "What is the physical demand of this journey?", a: "The Great Wall walk involves 10km of uneven terrain with some steep sections. All other activities are low-intensity." },
      { q: "Can this itinerary be customized?", a: "Every journey we design is completely bespoke. This is a suggested framework — we will adapt it entirely to your interests and pace." },
    ],
  },
  {
    id: "silk-road-odyssey",
    title: "The Silk Road Odyssey",
    subtitle: "Xi'an · Dunhuang · Kashgar",
    duration: "16 days",
    destinations: ["xian", "gansu", "xinjiang"],
    difficulty: "Moderate",
    image: "https://images.unsplash.com/photo-1474181487882-5abf3f0ba6c2?w=800&q=80",
    category: "Iconic",
    highlights: ["Mogao Caves private viewing", "Camel trek in the Gobi", "Kashgar Sunday bazaar", "Karakorum Highway drive"],
    overview: "The ancient Silk Road connected China to Rome across 7,000 kilometers of desert, mountain, and steppe. This journey follows its most dramatic section — from Xi'an's Tang Dynasty grandeur through Gansu's desert corridor to Xinjiang's Uyghur heartland — tracing the route that shaped the ancient world.",
    days: [
      { day: "Day 1–2", title: "Xi'an: The Eastern Gateway", description: "The Terracotta Army, city walls, and the Tang West Market — the Silk Road's eastern terminus." },
      { day: "Day 3–4", title: "Zhangye: Rainbow Mountains", description: "The Danxia Landform's extraordinary colored rock formations. Zhangye Dafo Temple." },
      { day: "Day 5–6", title: "Jiayuguan: The Last Gate", description: "The westernmost fort of the Great Wall. The desert beyond was once called 'the land of no return'." },
      { day: "Day 7–9", title: "Dunhuang: The Desert Oasis", description: "Mogao Caves private viewing with a specialist scholar. Camel trek to Crescent Moon Lake at sunset." },
      { day: "Day 10–11", title: "Urumqi & Heavenly Lake", description: "Flight to Xinjiang's capital. Day trip to the alpine Heavenly Lake above the clouds." },
      { day: "Day 12–14", title: "Kashgar: The Silk Road City", description: "The old city, Sunday livestock bazaar, and Id Kah Mosque. Uyghur home dinner." },
      { day: "Day 15–16", title: "Karakorum Highway", description: "Drive south along the Karakorum Highway toward the Pamirs. Karakul Lake with Muztagh Ata reflected in its waters." },
    ],
    accommodations: ["Sofitel Legend Xi'an", "Silk Road Dunhuang Hotel", "Qiniwak Hotel Kashgar"],
    experiences: ["Mogao Caves scholar tour", "Gobi camel trek", "Kashgar bazaar", "Karakorum Highway", "Uyghur cooking class"],
    expertNotes: "The Mogao Caves require advance booking for special access caves. We secure this for all our guests, including access to caves normally closed to the public.",
    faqs: [
      { q: "Is Xinjiang safe for travelers?", a: "Yes. We have operated journeys in Xinjiang for over 15 years and maintain close relationships with local guides and authorities. We brief all guests thoroughly before travel." },
      { q: "What is the altitude on this journey?", a: "Kashgar sits at 1,289m. The Karakorum Highway reaches 3,600m at Karakul Lake. We recommend acclimatization days and advise on altitude preparation." },
    ],
  },
  {
    id: "yunnan-mosaic",
    title: "The Yunnan Mosaic",
    subtitle: "Kunming · Dali · Lijiang · Shangri-La",
    duration: "14 days",
    destinations: ["yunnan"],
    difficulty: "Moderate",
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663786910793/nv3b3r8xSigzoBGpUx4ZRH/destination-yunnan-MgmXuu6XECuXSfSXdqH7Kn.webp",
    category: "Cultural",
    highlights: ["Tiger Leaping Gorge trek", "Naxi ancient music concert", "Tibetan monastery stay", "Yuanyang rice terraces at dawn"],
    overview: "Yunnan is China's most extraordinary province — a place where 26 ethnic groups have maintained distinct cultures, languages, and traditions for millennia. This journey moves through its most compelling landscapes and communities, from the Bai villages of Dali to the Tibetan highlands of Shangri-La.",
    days: [
      { day: "Day 1–2", title: "Kunming: The Spring City", description: "Stone Forest, Dianchi Lake, and the Green Lake Park teahouse culture." },
      { day: "Day 3–5", title: "Dali: Bai Culture", description: "The ancient walled city, Erhai Lake cycling, and a Bai village home visit." },
      { day: "Day 6–8", title: "Lijiang: Naxi World", description: "The UNESCO old town, Naxi ancient music, and Jade Dragon Snow Mountain." },
      { day: "Day 9–10", title: "Tiger Leaping Gorge", description: "Two-day trek through one of the world's deepest gorges." },
      { day: "Day 11–13", title: "Shangri-La", description: "Songzanlin Monastery, Pudacuo National Park, and Tibetan nomad communities." },
      { day: "Day 14", title: "Return to Kunming", description: "Scenic drive through the Yunnan highlands. Farewell dinner of Yunnan cuisine." },
    ],
    accommodations: ["Banyan Tree Lijiang", "Songtsam Shangri-La", "Linden Centre Dali"],
    experiences: ["Tiger Leaping Gorge trek", "Naxi music concert", "Bai village visit", "Tibetan monastery", "Yunnan cuisine"],
    expertNotes: "The Yuanyang rice terraces are best visited in January–April when water fills the terraces and reflects the sunrise sky. We can extend this journey to include them.",
    faqs: [
      { q: "How physically demanding is the Tiger Leaping Gorge trek?", a: "The upper trail is 22km over two days with significant elevation change. It requires good fitness. We can arrange a lower trail alternative for those who prefer a less strenuous option." },
    ],
  },
  {
    id: "yangtze-river-journey",
    title: "The Yangtze River Journey",
    subtitle: "Chongqing · Three Gorges · Wuhan",
    duration: "10 days",
    destinations: ["chongqing", "wuhan"],
    difficulty: "Easy",
    image: "https://images.unsplash.com/photo-1536599018102-9f803c140fc1?w=800&q=80",
    category: "Adventure",
    highlights: ["Three Gorges private cruise", "Fengdu Ghost City", "Shennong Stream boat", "Wuhan Yellow Crane Tower"],
    overview: "The Yangtze is the world's third-longest river and China's greatest waterway. This journey combines the dramatic mountain city of Chongqing with a private cruise through the Three Gorges — one of the world's most spectacular river passages — before arriving in the ancient city of Wuhan.",
    days: [
      { day: "Day 1–3", title: "Chongqing", description: "The mountain city's dramatic topography, hotpot culture, and Ciqikou ancient town." },
      { day: "Day 4–7", title: "Three Gorges Cruise", description: "Private cruise through Qutang, Wu, and Xiling Gorges. Shore excursions to Fengdu and Shennong Stream." },
      { day: "Day 8–10", title: "Wuhan", description: "Yellow Crane Tower, East Lake, and the Hubei Provincial Museum's Bronze Age collection." },
    ],
    accommodations: ["Capella Chongqing", "Victoria Cruises (private cabin)", "Wanda Reign Wuhan"],
    experiences: ["Three Gorges private cruise", "Shennong Stream boat", "Chongqing hotpot", "Bronze Age museum", "East Lake cycling"],
    expertNotes: "We use Victoria Cruises' smaller vessels rather than the large tourist ships — fewer passengers, better service, and more intimate shore excursions.",
    faqs: [
      { q: "What is the best time for the Three Gorges cruise?", a: "April–May and September–October offer the best weather and light. Summer can be extremely hot; winter is cold but atmospheric." },
    ],
  },
  {
    id: "tibet-pilgrimage",
    title: "The Tibet Pilgrimage",
    subtitle: "Lhasa · Gyantse · Shigatse · Everest",
    duration: "12 days",
    destinations: ["tibet"],
    difficulty: "Challenging",
    image: "https://images.unsplash.com/photo-1508804185872-d7badad00f7d?w=800&q=80",
    category: "Wellness",
    highlights: ["Potala Palace private access", "Everest Base Camp", "Namtso Lake at sunrise", "Tashilhunpo Monastery"],
    overview: "Tibet is the world's highest plateau — a land of extraordinary spiritual intensity and vast, humbling landscapes. This journey follows the ancient pilgrimage routes between Lhasa's sacred temples to the base of the world's highest mountain, with time to acclimatize and absorb the profound atmosphere of this remarkable place.",
    days: [
      { day: "Day 1–3", title: "Lhasa Acclimatization", description: "Gentle introduction to the city. Barkhor circuit, Jokhang Temple, and the Potala Palace." },
      { day: "Day 4", title: "Sera Monastery", description: "The famous monk debate at Sera Monastery. Drepung Monastery and Nechung Oracle Temple." },
      { day: "Day 5–6", title: "Gyantse & Shigatse", description: "Pelkor Chode Monastery's Kumbum stupa. Tashilhunpo Monastery, seat of the Panchen Lama." },
      { day: "Day 7–8", title: "Road to Everest", description: "Drive across the Tibetan plateau to Rongbuk Monastery — the world's highest monastery — with Everest filling the horizon." },
      { day: "Day 9", title: "Everest Base Camp", description: "Dawn at Everest Base Camp (5,364m). The world's highest mountain at close range." },
      { day: "Day 10–11", title: "Namtso Lake", description: "The sacred turquoise lake at 4,718m. Overnight at the lake for sunrise." },
      { day: "Day 12", title: "Return to Lhasa", description: "Final morning in Lhasa. Afternoon flight to Chengdu or Beijing." },
    ],
    accommodations: ["St. Regis Lhasa", "Rongbuk Monastery Guesthouse", "Namtso Lake Guesthouse"],
    experiences: ["Potala Palace", "Everest Base Camp", "Namtso Lake", "Monk debate", "Tibetan cooking"],
    expertNotes: "Tibet requires a special Tibet Travel Permit in addition to a Chinese visa. We handle all permit arrangements. A minimum of 3 acclimatization days in Lhasa is essential before proceeding to higher altitudes.",
    faqs: [
      { q: "What altitude will we reach?", a: "Lhasa is at 3,650m. Everest Base Camp is at 5,364m. Altitude sickness is a real consideration — we build in acclimatization days and carry emergency oxygen." },
      { q: "When is Tibet open to foreign visitors?", a: "Tibet is generally open from April to October. It closes to foreign visitors during politically sensitive periods. We monitor this closely and advise accordingly." },
    ],
  },
  {
    id: "ancient-villages",
    title: "Ancient Villages of Southern China",
    subtitle: "Anhui · Fujian · Guangdong",
    duration: "14 days",
    destinations: ["anhui", "fujian", "guangdong"],
    difficulty: "Easy",
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663786910793/nv3b3r8xSigzoBGpUx4ZRH/about-hero-WB6Ffx8gCWVUQwGjnBwSM4.webp",
    category: "Culinary",
    highlights: ["Huangshan sunrise above clouds", "Hongcun village photography", "Hakka tulou communities", "Kaiping Diaolou towers"],
    overview: "Southern China's ancient villages are among the world's most extraordinary architectural achievements — whitewashed Hui villages in Anhui, circular earthen fortresses in Fujian, and baroque watchtowers in Guangdong. This journey moves through them at a pace that allows genuine immersion in communities that have maintained their traditions for centuries.",
    days: [
      { day: "Day 1–4", title: "Anhui: Ink Painting Villages", description: "Huangshan at sunrise, Hongcun and Xidi villages, and the ancient Hui merchant culture." },
      { day: "Day 5–8", title: "Fujian: Earthen Fortresses", description: "The Hakka tulou clusters of Yongding and Nanjing counties. Community dinners with tulou residents." },
      { day: "Day 9–12", title: "Guangdong: Baroque Towers", description: "Kaiping's extraordinary Diaolou watchtowers, Foshan ancestral halls, and Guangzhou's food culture." },
      { day: "Day 13–14", title: "Hong Kong", description: "Final days in Hong Kong before departure." },
    ],
    accommodations: ["Bishan Bookstore Guesthouse", "Tulou Community Homestay", "Four Seasons Hong Kong"],
    experiences: ["Huangshan sunrise", "Tulou community stay", "Kaiping towers", "Cantonese food tour", "Village photography"],
    expertNotes: "We arrange homestays within the tulou communities — sleeping inside a 400-year-old circular fortress, sharing meals with the families who still live there, is one of the most extraordinary experiences in Chinese travel.",
    faqs: [
      { q: "Is the Huangshan hike difficult?", a: "The main trails involve significant stair climbing. Cable cars are available for those who prefer them. We recommend at least one day of hiking for the full experience." },
    ],
  },
];

export const blogPosts: BlogPost[] = [
  {
    id: "best-time-visit-china",
    title: "The Best Time to Visit China: A Month-by-Month Guide",
    category: "China Travel Guides",
    excerpt: "China's climate varies enormously across its vast territory. This guide helps you plan the perfect timing for your specific destinations and interests.",
    readTime: "12 min read",
    image: "https://images.unsplash.com/photo-1508804185872-d7badad00f7d?w=800&q=80",
    content: "",
    tags: ["China travel", "travel planning", "seasons", "climate"],
  },
  {
    id: "first-time-china-guide",
    title: "First-Time China Travel Guide: Everything You Need to Know",
    category: "China Travel Guides",
    excerpt: "Planning your first trip to China? This comprehensive guide covers visas, transport, communication, money, and cultural etiquette — everything a first-time visitor needs.",
    readTime: "18 min read",
    image: "https://images.unsplash.com/photo-1474181487882-5abf3f0ba6c2?w=800&q=80",
    content: "",
    tags: ["first time China", "China travel tips", "China guide", "travel planning"],
  },
  {
    id: "china-visa-guide",
    title: "China Visa Guide 2025: Requirements, Types & Application Process",
    category: "China Travel Guides",
    excerpt: "China's visa policies have changed significantly in recent years, with many countries now eligible for visa-free entry. Here is everything you need to know.",
    readTime: "10 min read",
    image: "https://images.unsplash.com/photo-1547981609-4b6bfe67ca0b?w=800&q=80",
    content: "",
    tags: ["China visa", "visa-free China", "travel documents", "China entry"],
  },
  {
    id: "undiscovered-china",
    title: "Beyond the Tourist Trail: China's Most Undiscovered Places",
    category: "Hidden China",
    excerpt: "The China that most visitors never see — remote valleys, forgotten towns, and landscapes of extraordinary beauty that remain largely unknown to international travelers.",
    readTime: "15 min read",
    image: "https://images.unsplash.com/photo-1548919973-5cef591cdbc9?w=800&q=80",
    content: "",
    tags: ["hidden China", "off beaten path", "undiscovered China", "secret China"],
  },
  {
    id: "yunnan-hidden-villages",
    title: "Hidden Villages of Yunnan: A Journey Through China's Most Diverse Province",
    category: "Hidden China",
    excerpt: "Yunnan's minority villages remain among the most authentic communities in China — places where ancient traditions, languages, and ways of life continue largely unchanged.",
    readTime: "14 min read",
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663786910793/nv3b3r8xSigzoBGpUx4ZRH/destination-yunnan-MgmXuu6XECuXSfSXdqH7Kn.webp",
    content: "",
    tags: ["Yunnan villages", "minority culture", "hidden Yunnan", "ethnic China"],
  },
  {
    id: "chinese-culture-guide",
    title: "Understanding Chinese Culture: An Essential Guide for Travelers",
    category: "Culture & People",
    excerpt: "Chinese culture is ancient, complex, and endlessly fascinating. This guide helps international travelers navigate customs, etiquette, and social dynamics with confidence and respect.",
    readTime: "16 min read",
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663786910793/nv3b3r8xSigzoBGpUx4ZRH/about-hero-WB6Ffx8gCWVUQwGjnBwSM4.webp",
    content: "",
    tags: ["Chinese culture", "cultural etiquette", "China customs", "travel culture"],
  },
  {
    id: "chinese-tea-culture",
    title: "The Art of Chinese Tea: A Traveler's Guide to Tea Culture",
    category: "Culture & People",
    excerpt: "Tea is not simply a drink in China — it is a philosophy, an art form, and a social ritual that has shaped Chinese civilization for three thousand years.",
    readTime: "13 min read",
    image: "https://images.unsplash.com/photo-1508804185872-d7badad00f7d?w=800&q=80",
    content: "",
    tags: ["Chinese tea", "tea culture", "tea ceremony", "Longjing tea"],
  },
  {
    id: "regional-chinese-food",
    title: "The Eight Great Cuisines of China: A Regional Food Guide",
    category: "Food & Culinary Travel",
    excerpt: "Chinese cuisine is not one cuisine — it is eight distinct culinary traditions, each shaped by geography, climate, and centuries of cultural development.",
    readTime: "17 min read",
    image: "https://images.unsplash.com/photo-1548919973-5cef591cdbc9?w=800&q=80",
    content: "",
    tags: ["Chinese food", "regional cuisine", "Sichuan food", "Cantonese food"],
  },
  {
    id: "street-food-china",
    title: "China's Street Food Culture: A City-by-City Guide",
    category: "Food & Culinary Travel",
    excerpt: "China's street food scene is one of the world's great culinary experiences — a democratic, democratic food culture where the best dishes often cost less than a dollar.",
    readTime: "14 min read",
    image: "https://images.unsplash.com/photo-1474181487882-5abf3f0ba6c2?w=800&q=80",
    content: "",
    tags: ["street food China", "Chinese street food", "food tour China", "local food"],
  },
  {
    id: "beijing-travel-guide",
    title: "Beijing Travel Guide: The Ultimate Insider's Companion",
    category: "Destination Guides",
    excerpt: "Beijing rewards those who look beyond the obvious. This guide reveals the imperial capital's hidden layers — from secret Hutong courtyards to contemporary art districts.",
    readTime: "20 min read",
    image: "https://images.unsplash.com/photo-1508804185872-d7badad00f7d?w=800&q=80",
    content: "",
    tags: ["Beijing guide", "Beijing travel", "Forbidden City", "Great Wall"],
  },
  {
    id: "shanghai-travel-guide",
    title: "Shanghai Travel Guide: Beyond the Bund",
    category: "Destination Guides",
    excerpt: "Shanghai is China's most cosmopolitan city — a place of extraordinary contrasts where Art Deco architecture faces futurist towers. This guide reveals its many layers.",
    readTime: "18 min read",
    image: "https://images.unsplash.com/photo-1474181487882-5abf3f0ba6c2?w=800&q=80",
    content: "",
    tags: ["Shanghai guide", "Shanghai travel", "Bund Shanghai", "French Concession"],
  },
  {
    id: "yunnan-travel-guide",
    title: "Yunnan Travel Guide: China's Most Extraordinary Province",
    category: "Destination Guides",
    excerpt: "Yunnan is unlike anywhere else in China — a province of extraordinary natural beauty, ethnic diversity, and cultural depth that rewards extended exploration.",
    readTime: "22 min read",
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663786910793/nv3b3r8xSigzoBGpUx4ZRH/destination-yunnan-MgmXuu6XECuXSfSXdqH7Kn.webp",
    content: "",
    tags: ["Yunnan guide", "Yunnan travel", "Lijiang", "Shangri-La"],
  },
  {
    id: "tibet-travel-guide",
    title: "Tibet Travel Guide: Planning Your Journey to the Roof of the World",
    category: "Destination Guides",
    excerpt: "Tibet requires more planning than any other destination in China — permits, acclimatization, and timing all matter enormously. This guide covers everything you need to know.",
    readTime: "19 min read",
    image: "https://images.unsplash.com/photo-1508804185872-d7badad00f7d?w=800&q=80",
    content: "",
    tags: ["Tibet guide", "Tibet travel", "Lhasa", "Everest Base Camp"],
  },
  {
    id: "xinjiang-travel-guide",
    title: "Xinjiang Travel Guide: China's Silk Road Frontier",
    category: "Destination Guides",
    excerpt: "Xinjiang is China's largest province — a vast landscape of desert, mountain, and oasis that was the heart of the ancient Silk Road. This guide helps you plan a journey of epic scale.",
    readTime: "21 min read",
    image: "https://images.unsplash.com/photo-1474181487882-5abf3f0ba6c2?w=800&q=80",
    content: "",
    tags: ["Xinjiang guide", "Kashgar", "Silk Road", "Dunhuang"],
  },
  {
    id: "rural-china-traditions",
    title: "Living Traditions: Rural China's Festivals and Ceremonies",
    category: "Culture & People",
    excerpt: "Away from China's cities, ancient festivals and ceremonies continue to mark the rhythms of rural life — harvest celebrations, ancestral rites, and minority festivals of extraordinary color.",
    readTime: "15 min read",
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663786910793/nv3b3r8xSigzoBGpUx4ZRH/about-hero-WB6Ffx8gCWVUQwGjnBwSM4.webp",
    content: "",
    tags: ["China festivals", "rural China", "Chinese traditions", "minority festivals"],
  },
  {
    id: "off-beaten-path-china",
    title: "Off the Beaten Path in China: 10 Destinations Most Visitors Miss",
    category: "Hidden China",
    excerpt: "China's most extraordinary experiences are often found far from the tourist trail. These ten destinations offer the depth, authenticity, and wonder that define truly memorable travel.",
    readTime: "16 min read",
    image: "https://images.unsplash.com/photo-1548919973-5cef591cdbc9?w=800&q=80",
    content: "",
    tags: ["off beaten path China", "hidden China", "alternative China", "undiscovered"],
  },
  {
    id: "food-guide-by-region",
    title: "China Food Guide by Region: What to Eat and Where",
    category: "Food & Culinary Travel",
    excerpt: "From Sichuan's numbing spice to Cantonese delicacy, from Xinjiang's lamb to Shanghai's sweet braised pork — China's regional food differences are as dramatic as its landscapes.",
    readTime: "20 min read",
    image: "https://images.unsplash.com/photo-1536599018102-9f803c140fc1?w=800&q=80",
    content: "",
    tags: ["China food regions", "Chinese cuisine guide", "what to eat China", "regional food"],
  },
  {
    id: "china-luxury-travel",
    title: "Luxury Travel in China: The Ultimate Guide to High-End Experiences",
    category: "China Travel Guides",
    excerpt: "China's luxury travel landscape has transformed dramatically in recent years. From ultra-luxury trains to private island resorts, this guide reveals the finest experiences available.",
    readTime: "18 min read",
    image: "https://images.unsplash.com/photo-1508804185872-d7badad00f7d?w=800&q=80",
    content: "",
    tags: ["luxury China travel", "high-end China", "luxury hotels China", "private tours"],
  },
  {
    id: "china-photography-guide",
    title: "China Photography Guide: The Best Locations and Golden Hours",
    category: "Hidden China",
    excerpt: "China offers some of the world's most extraordinary photography subjects — from the karst peaks of Guilin to the rice terraces of Yunnan. This guide reveals the best locations and timing.",
    readTime: "17 min read",
    image: "https://images.unsplash.com/photo-1547981609-4b6bfe67ca0b?w=800&q=80",
    content: "",
    tags: ["China photography", "photo locations China", "landscape photography", "travel photography"],
  },
  {
    id: "china-solo-travel",
    title: "Solo Travel in China: A Complete Safety and Logistics Guide",
    category: "China Travel Guides",
    excerpt: "China is one of the world's safest destinations for solo travelers. This guide covers everything from navigation apps to accommodation booking to staying connected.",
    readTime: "14 min read",
    image: "https://images.unsplash.com/photo-1474181487882-5abf3f0ba6c2?w=800&q=80",
    content: "",
    tags: ["solo travel China", "China safety", "China travel tips", "independent travel"],
  },
];

export const testimonials = [
  {
    id: 1,
    name: "James & Catherine Whitfield",
    country: "United Kingdom",
    trip: "Imperial Heartland, 12 days",
    rating: 5,
    text: "We have traveled extensively across Asia, but nothing prepared us for the depth of experience China Prime provided. Private access to the Terracotta Army at dusk, with our expert guide explaining the archaeology in extraordinary detail — it was the kind of moment that changes how you understand history.",
    avatar: "JW",
    author: "James & Catherine Whitfield",
    location: "United Kingdom",
  },
  {
    id: 2,
    name: "Michael van den Berg",
    country: "Netherlands",
    trip: "Yunnan Mosaic, 14 days",
    rating: 5,
    text: "The Tiger Leaping Gorge trek was the highlight of a journey full of highlights. Our guide knew every family along the trail — we were invited into homes, shared meals, and experienced a China that simply does not exist on the tourist circuit. Extraordinary.",
    avatar: "MB",
    author: "Michael van den Berg",
    location: "Netherlands",
  },
  {
    id: 3,
    name: "Sarah & Tom Kowalski",
    country: "United States",
    trip: "Tibet Pilgrimage, 12 days",
    rating: 5,
    text: "We were nervous about Tibet — the altitude, the permits, the logistics. China Prime handled everything flawlessly. Standing at Everest Base Camp at dawn, with the mountain turning pink in the first light, was the most profound experience of our lives.",
    avatar: "SK",
    author: "Sarah & Tom Kowalski",
    location: "United States",
  },
  {
    id: 4,
    name: "François & Marie Dubois",
    country: "France",
    trip: "Silk Road Odyssey, 16 days",
    rating: 5,
    text: "The Mogao Caves private viewing with a specialist scholar was worth the entire journey. To stand in a cave painted 1,400 years ago, with only our small group and an expert who has dedicated his life to understanding these murals — it was humbling and extraordinary.",
    avatar: "FD",
    author: "François & Marie Dubois",
    location: "France",
  },
  {
    id: 5,
    name: "Emma Richardson",
    country: "Australia",
    trip: "Ancient Villages, 14 days",
    rating: 5,
    text: "Sleeping inside a 400-year-old Hakka tulou, sharing dinner with the family who has lived there for generations — this is the kind of experience that only a company with deep local relationships can provide. I have recommended China Prime to everyone I know.",
    avatar: "ER",
    author: "Emma Richardson",
    location: "Australia",
  },
  {
    id: 6,
    name: "Henrik & Astrid Larsson",
    country: "Sweden",
    trip: "Yangtze River Journey, 10 days",
    rating: 5,
    text: "The Three Gorges on a small private vessel rather than a large cruise ship made all the difference. We could stop when we wanted, go ashore spontaneously, and experience the gorges at our own pace. The attention to detail throughout was exceptional.",
    avatar: "HL",
    author: "Henrik & Astrid Larsson",
    location: "Sweden",
  },
  {
    id: 7,
    name: "Priya & Rajesh Patel",
    country: "India",
    trip: "Himalayan Escape, 10 days",
    rating: 5,
    text: "Our family was hesitant about traveling with young children to remote areas. China Prime's planning was so thoughtful — every accommodation, every meal, every activity was perfectly suited to our needs. Our children still talk about the monks we met at the monastery.",
    avatar: "PR",
    author: "Priya & Rajesh Patel",
    location: "India",
  },
  {
    id: 8,
    name: "David Chen",
    country: "Singapore",
    trip: "Culinary Immersion, 8 days",
    rating: 5,
    text: "As a food writer, I have high standards. China Prime exceeded every expectation. Learning to make hand-pulled noodles from a master in Xi'an, then dining in a private chef's home in Chengdu — these are the experiences that define a lifetime of travel.",
    avatar: "DC",
    author: "David Chen",
    location: "Singapore",
  },
  {
    id: 9,
    name: "Isabella & Marco Rossi",
    country: "Italy",
    trip: "Imperial Heartland, 12 days",
    rating: 5,
    text: "We have traveled to 60 countries. This journey to China was among our top three experiences ever. The combination of iconic sites, intimate cultural moments, and impeccable service was simply unmatched. We are already planning our return.",
    avatar: "IR",
    author: "Isabella & Marco Rossi",
    location: "Italy",
  },
  {
    id: 10,
    name: "Amelia Thompson",
    country: "Canada",
    trip: "Women's Wellness Retreat, 9 days",
    rating: 5,
    text: "The women-only wellness journey was transformative. Practicing tai chi at sunrise in a traditional garden, meditation sessions with Buddhist nuns, and deep conversations with fellow travelers — I returned home feeling renewed and inspired.",
    avatar: "AT",
    author: "Amelia Thompson",
    location: "Canada",
  },
  {
    id: 11,
    name: "Klaus Mueller",
    country: "Germany",
    trip: "Photography Expedition, 11 days",
    rating: 5,
    text: "As a professional photographer, I needed a guide who understood light, composition, and access to unique locations. China Prime delivered on all fronts. The images I captured during this journey are among my finest work.",
    avatar: "KM",
    author: "Klaus Mueller",
    location: "Germany",
  },
  {
    id: 12,
    name: "Yuki & Hiroshi Tanaka",
    country: "Japan",
    trip: "Ancient Temples, 13 days",
    rating: 5,
    text: "We visited 15 temples on this journey, each one explained with deep historical knowledge by our guide. The private evening access to Shaolin Temple, with the monks demonstrating their martial arts, was a highlight we will treasure forever.",
    avatar: "YT",
    author: "Yuki & Hiroshi Tanaka",
    location: "Japan",
  },
  {
    id: 13,
    name: "Sophia & Lucas Ferreira",
    country: "Brazil",
    trip: "Silk Road Odyssey, 16 days",
    rating: 5,
    text: "From the bustling markets of Xi'an to the remote Taklamakan Desert, every moment was carefully orchestrated. Our guide's passion for the Silk Road history was infectious, and we learned more than we ever expected.",
    avatar: "SF",
    author: "Sophia & Lucas Ferreira",
    location: "Brazil",
  },
  {
    id: 14,
    name: "Margaret & Robert MacLeod",
    country: "Scotland",
    trip: "Senior Adventure, 10 days",
    rating: 5,
    text: "At 72 and 75, we were concerned about keeping up. China Prime adapted every activity to our pace and interests. We experienced more authentic China in 10 days than we could have imagined, and we felt safe and cared for throughout.",
    avatar: "MM",
    author: "Margaret & Robert MacLeod",
    location: "Scotland",
  },
];
