import { destinationAsset } from "@/content/destinations/assets";
import { homeEditorialImages } from "@/content/home/homepage";
import {
  chengduImages,
  chongqingImages,
  zhangjiajieImages,
} from "@/content/tours/chengdu-chongqing-zhangjiajie-assets";
import type { JournalArticle } from "@/types/journal";

const author = {
  name: "AVIORA Travel Team",
  role: "China travel specialists",
};

const journalImages = {
  chengduDays: {
    src: "/tours/chengdu-chongqing-zhangjiajie-private-11-day-tour/chengdu-12.webp",
    alt: "A giant panda eating bamboo during a morning visit in Chengdu",
    width: 1600,
    height: 1067,
    objectPosition: "50% 48%",
  },
  chongqingThreeDay: {
    src: "/tours/chengdu-chongqing-zhangjiajie-private-11-day-tour/chongqing-01.webp",
    alt: "Chongqing's layered skyline during the blue hour",
    width: 1600,
    height: 1067,
    objectPosition: "50% 48%",
  },
  zhangjiajieStay: {
    src: "/tours/chengdu-chongqing-zhangjiajie-private-11-day-tour/zhangjiajie-15.webp",
    alt: "Zhangjiajie's quartz-sandstone pillars emerging from morning mist",
    width: 1600,
    height: 1067,
    objectPosition: "50% 48%",
  },
  chengduChongqingZhangjiajie: {
    src: "/tours/chengdu-chongqing-zhangjiajie-private-11-day-tour/hero-01.webp",
    alt: "International travelers looking across Zhangjiajie's sandstone peaks",
    width: 1600,
    height: 1067,
    objectPosition: "50% 46%",
  },
  chengduChongqingZhangjiajieChengdu: {
    src: "/tours/chengdu-chongqing-zhangjiajie-private-11-day-tour/chengdu-01.webp",
    alt: "Giant panda resting in a green habitat in Chengdu",
    width: 1600,
    height: 1067,
    objectPosition: "50% 48%",
  },
  chengduChongqingZhangjiajieChongqing: {
    src: "/tours/chengdu-chongqing-zhangjiajie-private-11-day-tour/chongqing-01.webp",
    alt: "Chongqing's layered skyline during the blue hour",
    width: 1600,
    height: 1067,
    objectPosition: "50% 48%",
  },
  chengduChongqingZhangjiajieForest: {
    src: "/tours/chengdu-chongqing-zhangjiajie-private-11-day-tour/zhangjiajie-01.webp",
    alt: "Forest and sandstone peaks in Zhangjiajie National Forest Park",
    width: 1600,
    height: 1067,
    objectPosition: "50% 48%",
  },
  privateChinaTourCost: {
    src: "/home/editorial/great-wall-private-china-travel.webp",
    alt: "Private travelers walking on the Great Wall during a tailored China journey",
    width: 1086,
    height: 1448,
    objectPosition: "50% 48%",
  },
  tenDayChinaItinerary: {
    src: "/tours/first-china-beautifully-paced/shanghai-waterfront-group.webp",
    alt: "International visitors beside the Shanghai waterfront on a first China journey",
    width: 1920,
    height: 1440,
    objectPosition: "50% 50%",
  },
  singaporePrivateChinaTour: {
    src: "/home/editorial/travel-trade-team-singapore.webp",
    alt: "AVIORA China travel specialists meeting international travel partners in Singapore",
    width: 1080,
    height: 810,
    objectPosition: "50% 48%",
  },
  visaFreeTransit: {
    src: "/journal/2026-08-06/visa-free-transit-shanghai.webp",
    alt: "International visitors on the Bund with the Shanghai skyline behind them",
    width: 1620,
    height: 1080,
    objectPosition: "50% 52%",
  },
  accommodationRegistration: {
    src: "/journal/2026-08-06/accommodation-registration-check-in.webp",
    alt: "International guests with hotel staff at a reception in China",
    width: 1706,
    height: 1279,
    objectPosition: "50% 58%",
  },
  highSpeedTrain: {
    src: "/journal/2026-08-06/china-high-speed-train-boarding.webp",
    alt: "International traveler beside a high-speed train platform in China",
    width: 2400,
    height: 3200,
    objectPosition: "50% 48%",
  },
  mobilePayment: {
    src: "/journal/2026-08-06/china-mobile-payment.webp",
    alt: "Traveler completing a mobile payment at a counter in China",
    width: 2400,
    height: 3200,
    objectPosition: "50% 57%",
  },
  forbiddenCityEntrance: {
    src: "/journal/2026-08-06/forbidden-city-entrance.webp",
    alt: "Bronze guardian lion at the entrance to the Forbidden City in Beijing",
    width: 2400,
    height: 3199,
    objectPosition: "64% 60%",
  },
  chengduPandaBase: {
    src: "/journal/2026-08-07/chengdu-panda-base-hero.webp",
    alt: "Two giant pandas resting and feeding on wooden platforms at Chengdu Panda Base",
    width: 1800,
    height: 1200,
    objectPosition: "50% 48%",
  },
  chengduPandasPlatform: {
    src: "/journal/2026-08-07/chengdu-pandas-platform.webp",
    alt: "Two giant pandas resting and feeding on wooden platforms at Chengdu Panda Base",
    width: 1200,
    height: 1600,
    objectPosition: "50% 48%",
  },
  chengduPandaClose: {
    src: "/journal/2026-08-07/chengdu-panda-close-view.webp",
    alt: "A giant panda walking through a wooded enclosure at Chengdu Panda Base",
    width: 1200,
    height: 1600,
    objectPosition: "50% 52%",
  },
  simCardAirport: {
    src: "/journal/2026-08-07/china-sim-card-airport-counter-hero.webp",
    alt: "China Unicom tourist SIM card counter at Beijing Daxing International Airport",
    width: 1800,
    height: 1200,
    objectPosition: "50% 48%",
  },
  simCardCounter: {
    src: "/journal/2026-08-07/china-sim-card-airport-counter.webp",
    alt: "China Unicom tourist SIM card counter at Beijing Daxing International Airport",
    width: 1200,
    height: 1600,
    objectPosition: "50% 48%",
  },
  simCardPlanBoard: {
    src: "/journal/2026-08-07/china-unicom-tourist-sim-plan-board.webp",
    alt: "Printed China Unicom tourist SIM plan board at Beijing Daxing International Airport",
    width: 1200,
    height: 1600,
    objectPosition: "50% 52%",
  },
  shanghaiAirportGuide: {
    src: "/home/shanghai-pudong-skyline.webp",
    alt: "Shanghai Pudong skyline seen across the Huangpu River",
    width: 1920,
    height: 1080,
    objectPosition: "50% 45%",
  },
  goldenWeekRail: {
    src: "/journal/2026-08-08/china-golden-week-high-speed-rail-hero.webp",
    alt: "Fuxing high-speed trains lined up at Shenzhen North Railway Station",
    width: 1800,
    height: 1200,
    objectPosition: "50% 52%",
  },
  goldenWeekRailPortrait: {
    src: "/journal/2026-08-08/shenzhen-north-high-speed-trains.webp",
    alt: "Fuxing high-speed trains lined up at Shenzhen North Railway Station",
    width: 1200,
    height: 1803,
    objectPosition: "50% 50%",
  },
  greatWallComparison: {
    src: "/tours/beijing-unhurried/great-wall-walk.webp",
    alt: "Cable car beside Great Wall ramparts crossing a mountain ridge",
    width: 2400,
    height: 1641,
    objectPosition: "50% 48%",
  },
  greatWallOverview: {
    src: "/tours/beijing-unhurried/great-wall-overview.webp",
    alt: "Great Wall ramparts crossing forested mountains near Beijing",
    width: 864,
    height: 1488,
    objectPosition: "50% 46%",
  },
  terracottaArmy: {
    src: "/home/xian-terracotta-army.webp",
    alt: "Rows of terracotta warriors inside the Qin Shi Huang Mausoleum Museum",
    width: 1400,
    height: 927,
    objectPosition: "50% 48%",
  },
  terracottaPortrait: {
    src: "/tours/first-china-beautifully-paced/xian-terracotta-army-portrait.webp",
    alt: "Individual terracotta warrior showing detailed armor and facial features",
    width: 1440,
    height: 1920,
    objectPosition: "50% 45%",
  },
  powerBank: {
    src: "/journal/2026-08-08/china-domestic-flight-power-bank-hero.webp",
    alt: "Power bank and charging cable inside a passenger's carry-on bag",
    width: 1800,
    height: 1200,
    objectPosition: "50% 50%",
  },
  powerBankCarryOn: {
    src: "/journal/2026-08-08/power-bank-in-carry-on-bag.webp",
    alt: "Power bank and charging cable inside a passenger's carry-on bag",
    width: 1200,
    height: 1600,
    objectPosition: "50% 50%",
  },
  medicine: {
    src: "/journal/2026-08-08/bringing-medicine-to-china-hero.webp",
    alt: "Several medicines kept in their labeled original packaging for travel",
    width: 1800,
    height: 1200,
    objectPosition: "50% 50%",
  },
  medicinePackaging: {
    src: "/journal/2026-08-08/medicine-in-original-packaging.webp",
    alt: "Several medicines kept in their labeled original packaging for travel",
    width: 1200,
    height: 1600,
    objectPosition: "50% 50%",
  },
  medicineList: {
    src: "/journal/2026-08-08/personal-medicine-declaration-list.webp",
    alt: "Example bilingual personal medicine declaration list",
    width: 1200,
    height: 1600,
    objectPosition: "50% 46%",
  },
} as const;

export const publishedJournalArticles: JournalArticle[] = [
  {
    slug: "how-many-days-in-chengdu-itinerary",
    title: "How Many Days in Chengdu? A 3-to-5-Day Planning Guide",
    dek: "Choose the right Chengdu stay length for pandas, tea houses, Sichuan food, families and a wider private China route.",
    excerpt:
      "A practical answer for three, four or five days in Chengdu, with panda timing, hotel logic, food planning and product routes.",
    category: "Destinations",
    tags: ["chengdu", "pandas", "food", "family-travel", "slow-travel"],
    author,
    publishedAt: "2026-08-12",
    readingTime: "11 min read",
    editorPick: true,
    hero: { eyebrow: "Chengdu stay planning", image: journalImages.chengduDays },
    gallery: [chengduImages[3], chengduImages[15], chengduImages[17]],
    content: [],
    seo: {
      title: "How Many Days in Chengdu? 3-to-5-Day Itinerary",
      description:
        "Decide how many days to spend in Chengdu with realistic plans for pandas, tea houses, Sichuan food, families and a wider private China route.",
      keywords: [
        "how many days in Chengdu",
        "Chengdu itinerary 3 days",
        "Chengdu itinerary 5 days",
        "how long to stay in Chengdu",
        "Chengdu panda itinerary",
      ],
      ogImage: journalImages.chengduDays,
    },
    related: {
      destinations: ["chengdu"],
      tours: ["chengdu-pandas-sichuan-table", "chengdu-chongqing-zhangjiajie-private-11-day-tour"],
      experiences: ["pandas", "food", "private-guides"],
      articles: [
        "chengdu-panda-base-tickets-foreigners",
        "chengdu-chongqing-zhangjiajie-itinerary",
      ],
    },
    conversion: {
      eyebrow: "Choose the right Chengdu pace",
      title: "Know whether Chengdu needs three or five days.",
      description:
        "Share your dates, travelers and wider route. AVIORA will recommend a stay length and explain what fits before preparing the proposal.",
      label: "Plan My Chengdu Stay",
      href: "/start-planning?source=journal-chengdu-days",
    },
    sourcePath: "content/journal/articles/2026-08-12-how-many-days-in-chengdu-itinerary.md",
  },
  {
    slug: "3-day-chongqing-itinerary",
    title: "A 3-Day Chongqing Itinerary That Respects the City",
    dek: "Plan Chongqing by geography, food and city levels, with realistic day and night routes, hotel logic and private transport support.",
    excerpt:
      "A three-day Chongqing plan that explains the vertical city without reducing it to a list of viral viewpoints.",
    category: "Destinations",
    tags: ["chongqing", "food", "photography", "family-travel", "private-guides"],
    author,
    publishedAt: "2026-08-12",
    readingTime: "10 min read",
    editorPick: true,
    hero: { eyebrow: "Chongqing city planning", image: journalImages.chongqingThreeDay },
    gallery: [chongqingImages[2], chongqingImages[11], chongqingImages[15]],
    content: [],
    seo: {
      title: "3-Day Chongqing Itinerary: What to See and Where to Stay",
      description:
        "Plan three days in Chongqing with realistic routes for its vertical streets, river views, hotpot, night photography, hotels and private transport.",
      keywords: [
        "3 day Chongqing itinerary",
        "Chongqing itinerary",
        "how many days in Chongqing",
        "where to stay in Chongqing",
        "Chongqing private tour",
      ],
      ogImage: journalImages.chongqingThreeDay,
    },
    related: {
      destinations: ["chongqing"],
      tours: ["chengdu-chongqing-zhangjiajie-private-11-day-tour"],
      experiences: ["food", "private-guides"],
      articles: ["chengdu-chongqing-zhangjiajie-itinerary", "private-china-tour-cost-2026"],
    },
    conversion: {
      eyebrow: "Plan the vertical city properly",
      title: "Build Chongqing around levels, transfers and real interests.",
      description:
        "Share your dates, party, food interests and walking comfort. AVIORA will connect the hotel, transport, night route and open day.",
      label: "Plan My Chongqing Route",
      href: "/start-planning?source=journal-chongqing-3-day",
    },
    sourcePath: "content/journal/articles/2026-08-12-3-day-chongqing-itinerary.md",
  },
  {
    slug: "where-to-stay-in-zhangjiajie",
    title: "Where to Stay in Zhangjiajie: Wulingyuan or the City?",
    dek: "Compare Wulingyuan and Zhangjiajie City by park access, Tianmen Mountain, airport transfers, walking load and a realistic mountain route.",
    excerpt:
      "A practical accommodation guide that helps you choose the right Zhangjiajie base before booking the hotel.",
    category: "Destinations",
    tags: ["zhangjiajie", "nature", "photography", "family-travel", "private-guides"],
    author,
    publishedAt: "2026-08-12",
    readingTime: "11 min read",
    editorPick: true,
    hero: { eyebrow: "Zhangjiajie stay planning", image: journalImages.zhangjiajieStay },
    gallery: [zhangjiajieImages[0], zhangjiajieImages[17], zhangjiajieImages[19]],
    content: [],
    seo: {
      title: "Where to Stay in Zhangjiajie: Wulingyuan vs City",
      description:
        "Compare Wulingyuan and Zhangjiajie City hotels by park access, Tianmen Mountain, airport transfers, walking load and a realistic 3-to-4-night route.",
      keywords: [
        "where to stay in Zhangjiajie",
        "Wulingyuan or Zhangjiajie City",
        "how many days in Zhangjiajie",
        "Zhangjiajie itinerary 4 days",
        "Zhangjiajie hotel near national park",
      ],
      ogImage: journalImages.zhangjiajieStay,
    },
    related: {
      destinations: ["zhangjiajie"],
      tours: [
        "shanghai-zhangjiajie-floating-peaks",
        "chengdu-chongqing-zhangjiajie-private-11-day-tour",
      ],
      experiences: ["private-guides"],
      articles: ["chengdu-chongqing-zhangjiajie-itinerary", "private-china-tour-cost-2026"],
    },
    conversion: {
      eyebrow: "Choose the right mountain base",
      title: "Select Wulingyuan or the city before you book the room.",
      description:
        "Share your arrival, departure, park priorities and walking preferences. AVIORA will recommend the base and sequence before preparing the proposal.",
      label: "Plan My Zhangjiajie Stay",
      href: "/start-planning?source=journal-zhangjiajie-stay",
    },
    sourcePath: "content/journal/articles/2026-08-12-where-to-stay-in-zhangjiajie.md",
  },
  {
    slug: "chengdu-chongqing-zhangjiajie-itinerary",
    title: "11-Day Chengdu, Chongqing & Zhangjiajie Itinerary",
    dek: "Connect pandas, Sichuan food, Chongqing's vertical cityscape and Zhangjiajie's mountain scenery without turning the trip into a transfer schedule.",
    excerpt:
      "A practical 11-day route with realistic city stays, weather-aware mountain days, physical-load advice and two flexible days.",
    category: "Destinations",
    tags: ["chengdu", "chongqing", "zhangjiajie", "nature", "food", "photography"],
    author,
    publishedAt: "2026-08-12",
    readingTime: "13 min read",
    featured: true,
    editorPick: true,
    hero: {
      eyebrow: "Three-region private route",
      image: journalImages.chengduChongqingZhangjiajie,
    },
    gallery: [
      journalImages.chengduChongqingZhangjiajieChengdu,
      journalImages.chengduChongqingZhangjiajieChongqing,
      journalImages.chengduChongqingZhangjiajieForest,
    ],
    content: [],
    seo: {
      title: "11-Day Chengdu, Chongqing & Zhangjiajie Itinerary",
      description:
        "Plan an 11-day Chengdu, Chongqing and Zhangjiajie trip with pandas, Sichuan food, mountain scenery, open days and private local support.",
      keywords: [
        "Chengdu Chongqing Zhangjiajie itinerary",
        "11 day China itinerary Chengdu Chongqing Zhangjiajie",
        "Chengdu Chongqing Zhangjiajie tour",
        "private Zhangjiajie itinerary",
        "China panda and Zhangjiajie tour",
      ],
      ogImage: journalImages.chengduChongqingZhangjiajie,
    },
    related: {
      destinations: ["chengdu", "chongqing", "zhangjiajie"],
      tours: [
        "chengdu-chongqing-zhangjiajie-private-11-day-tour",
        "chengdu-pandas-sichuan-table",
        "shanghai-zhangjiajie-floating-peaks",
      ],
      experiences: ["pandas", "food", "private-guides"],
      articles: [
        "chengdu-panda-base-tickets-foreigners",
        "10-day-china-itinerary-first-time-visitors",
        "private-china-tour-cost-2026",
      ],
    },
    conversion: {
      eyebrow: "Shape the three-region route",
      title: "Decide the pace before we price the trip.",
      description:
        "Share your dates, party, hotel expectations and walking preferences. We will recommend the transport, open-day use and mountain pacing before preparing the proposal.",
      label: "Request the 11-Day Proposal",
      href: "/start-planning?source=journal-ccz-itinerary",
    },
    sourcePath: "content/journal/articles/2026-08-12-chengdu-chongqing-zhangjiajie-itinerary.md",
  },
  {
    slug: "private-china-tour-cost-2026",
    title: "How Much Does a Private China Tour Cost in 2026?",
    dek: "Understand the hotel, guide, transport and service decisions behind a private China quotation before comparing the total price.",
    excerpt:
      "A transparent guide to private China tour costs, price drivers and the questions that make two quotations genuinely comparable.",
    category: "Luxury Travel",
    tags: ["first-time-china", "luxury-travel", "family-travel", "private-guides"],
    author,
    publishedAt: "2026-08-10",
    readingTime: "12 min read",
    editorPick: true,
    hero: { eyebrow: "Tour price planning", image: journalImages.privateChinaTourCost },
    gallery: [
      journalImages.privateChinaTourCost,
      journalImages.tenDayChinaItinerary,
      destinationAsset.shanghaiSkyline,
    ],
    content: [],
    seo: {
      title: "Private China Tour Cost in 2026: Price Guide",
      description:
        "Understand private China tour costs in 2026, including hotels, guides, transport, tickets and the questions needed for a comparable quotation.",
      keywords: [
        "private China tour cost",
        "how much does a private China tour cost",
        "China private tour price",
        "China tour cost 2026",
        "luxury China tour cost",
      ],
      ogImage: journalImages.privateChinaTourCost,
    },
    related: {
      destinations: ["beijing", "xian", "shanghai"],
      tours: ["first-china-beautifully-paced", "beijing-xian-chengdu-shanghai-private-11-day-tour"],
      experiences: ["private-guides", "train-travel"],
      articles: ["10-day-china-itinerary-first-time-visitors", "private-china-tour-from-singapore"],
    },
    conversion: {
      eyebrow: "A clearer quotation",
      title: "Receive a China tour proposal you can compare properly.",
      description:
        "Share your dates, travelers, hotel expectations and preferred route. We will explain the route assumptions and principal inclusions before asking you to decide.",
      label: "Request My Costed Proposal",
      href: "/start-planning?source=journal-cost-guide",
    },
    sourcePath: "content/journal/articles/2026-08-10-private-china-tour-cost-2026.md",
  },
  {
    slug: "10-day-china-itinerary-first-time-visitors",
    title: "The Best 10-Day China Itinerary for First-Time Visitors",
    dek: "Use Beijing, Xi’an and Shanghai to build a first China trip with realistic travel days, three strong city chapters and room to enjoy them.",
    excerpt:
      "A day-by-day Beijing, Xi’an and Shanghai route with practical pacing, transport choices and alternatives for families and older travelers.",
    category: "Travel Guides",
    tags: ["first-time-china", "beijing", "xian", "shanghai", "train-travel"],
    author,
    publishedAt: "2026-08-10",
    readingTime: "14 min read",
    editorPick: true,
    hero: { eyebrow: "First China itinerary", image: journalImages.tenDayChinaItinerary },
    gallery: [
      journalImages.tenDayChinaItinerary,
      destinationAsset.beijingForbiddenCityWide,
      journalImages.terracottaArmy,
    ],
    content: [],
    seo: {
      title: "10-Day China Itinerary for First-Time Visitors",
      description:
        "Plan 10 days in China with Beijing, Xi’an and Shanghai, realistic travel time, a Great Wall day and practical private-tour pacing.",
      keywords: [
        "10 day China itinerary",
        "China itinerary 10 days",
        "first time China itinerary",
        "Beijing Xi'an Shanghai itinerary",
        "10 days in China",
      ],
      ogImage: journalImages.tenDayChinaItinerary,
    },
    related: {
      destinations: ["beijing", "xian", "shanghai"],
      tours: ["first-china-beautifully-paced", "beijing-xian-chengdu-shanghai-private-11-day-tour"],
      experiences: ["private-guides", "train-travel"],
      articles: [
        "private-china-tour-cost-2026",
        "china-high-speed-train-foreigners",
        "mutianyu-badaling-jinshanling-great-wall",
      ],
    },
    conversion: {
      eyebrow: "Your ten-day route",
      title: "Make the classic itinerary fit the people taking it.",
      description:
        "Tell us your dates, interests and walking preferences. We will adjust the city sequence, transport and daily load before preparing the proposal.",
      label: "Shape My 10-Day Route",
      href: "/start-planning?source=journal-10-day-itinerary",
    },
    sourcePath: "content/journal/articles/2026-08-10-10-day-china-itinerary-first-time-visitors.md",
  },
  {
    slug: "private-china-tour-from-singapore",
    title: "How to Plan a Private China Tour from Singapore",
    dek: "Choose the route, gateways, hotels and local support for a private China holiday designed around travelers departing from Singapore.",
    excerpt:
      "A Singapore-focused planning guide covering trip length, route ideas, entry checks, payments, families and Muslim-friendly requirements.",
    category: "Travel Guides",
    tags: ["singapore", "first-time-china", "family-travel", "muslim-friendly"],
    author,
    publishedAt: "2026-08-10",
    readingTime: "13 min read",
    editorPick: true,
    hero: {
      eyebrow: "Singapore to China",
      image: journalImages.singaporePrivateChinaTour,
    },
    gallery: [
      journalImages.singaporePrivateChinaTour,
      journalImages.tenDayChinaItinerary,
      destinationAsset.chengduPanda,
    ],
    content: [],
    seo: {
      title: "Private China Tour from Singapore: Planning Guide",
      description:
        "Plan a private China tour from Singapore with route ideas, flight logic, entry checks, payments, family pacing and local support.",
      keywords: [
        "private China tour from Singapore",
        "China private tour package from Singapore",
        "China itinerary from Singapore",
        "China tour for Singapore travellers",
        "Muslim friendly China private tour",
      ],
      ogImage: journalImages.singaporePrivateChinaTour,
    },
    related: {
      destinations: ["beijing", "xian", "chengdu", "shanghai"],
      tours: [
        "first-china-beautifully-paced",
        "beijing-xian-chengdu-shanghai-private-11-day-tour",
        "chengdu-pandas-sichuan-table",
      ],
      experiences: ["private-guides", "train-travel", "food"],
      articles: [
        "10-day-china-itinerary-first-time-visitors",
        "private-china-tour-cost-2026",
        "china-mobile-payments-foreign-tourists",
      ],
    },
    conversion: {
      eyebrow: "Singapore to China",
      title: "Plan the route before committing to the wrong flights.",
      description:
        "Share your travel window, party and priorities. We will suggest the right arrival city, trip length and route for a private journey from Singapore.",
      label: "Plan From Singapore",
      href: "/start-planning?source=journal-singapore-guide",
    },
    sourcePath: "content/journal/articles/2026-08-10-private-china-tour-from-singapore.md",
  },
  {
    slug: "aviora-ttg-asia-matta-connect-2026",
    title: "Listening Before Designing: AVIORA at MATTA Connect",
    dek: "TTG Asia named Guohui Shi of China Prime DMC, AVIORA's China operating team, in its MATTA Connect 2026 coverage. The more important story is why listening comes before itinerary design.",
    excerpt:
      "How AVIORA turns conversations with Malaysian travel buyers into clearer, more considerate private journeys through China.",
    category: "Industry News",
    tags: ["travel-trade", "malaysia", "muslim-friendly", "private-guides"],
    author,
    publishedAt: "2026-08-08",
    readingTime: "6 min read",
    featured: true,
    editorPick: true,
    hero: {
      eyebrow: "AVIORA in the travel trade",
      image: homeEditorialImages.tradeBuyerMeeting,
    },
    gallery: [homeEditorialImages.tradeMuslimBuyers, homeEditorialImages.tradeConsultation],
    content: [],
    seo: {
      title: "AVIORA at MATTA Connect | Featured in TTG Asia",
      description:
        "TTG Asia named Guohui Shi of AVIORA's China operating team in its MATTA Connect coverage. Read how listening shapes more thoughtful private China journeys.",
      keywords: [
        "AVIORA MATTA Connect",
        "AVIORA private China travel",
        "China Prime DMC TTG Asia",
        "China Prime DMC MATTA Connect",
        "Guohui Shi China Prime DMC",
        "China inbound travel specialist",
        "Malaysia China private travel",
      ],
      ogImage: homeEditorialImages.tradeBuyerMeeting,
    },
    related: {
      tours: [
        "first-china-beautifully-paced",
        "chengdu-pandas-jiuzhaigou-private-7-day-tour",
        "xian-beijing-terracotta-warriors-great-wall-private-6-day-tour",
      ],
      articles: ["china-240-hour-visa-free-transit-guide", "china-high-speed-train-foreigners"],
    },
    citations: [
      {
        name: "MATTA Connect gains traction as B2B platform",
        url: "https://www.ttgasia.com/2026/07/30/matta-connect-gains-traction-as-b2b-platform/",
        publisher: "TTG Asia",
        publishedAt: "2026-07-30",
      },
    ],
    sourcePath: "content/journal/articles/2026-08-08-china-prime-dmc-ttg-asia-matta-connect.md",
  },
  {
    slug: "china-240-hour-visa-free-transit-guide",
    title: "China’s 240-Hour Visa-Free Transit: A Route-First Guide",
    dek: "Check nationality, ports, onward routing and permitted areas before building a visa-free China stopover.",
    excerpt:
      "A route-first explanation of China’s 240-hour transit policy for travelers planning Beijing, Shanghai or another eligible stopover.",
    category: "Visa",
    tags: ["first-time-china", "beijing", "shanghai", "private-guides"],
    author,
    publishedAt: "2026-08-06",
    readingTime: "10 min read",
    hero: { eyebrow: "Entry planning", image: journalImages.visaFreeTransit },
    gallery: [journalImages.visaFreeTransit, destinationAsset.beijingForbiddenCityWide],
    content: [],
    seo: {
      title: "China 240-Hour Visa-Free Transit Guide 2026",
      description:
        "Check China’s 240-hour visa-free transit rules, eligible routes, ports and permitted areas before building a Beijing or Shanghai stopover.",
      keywords: [
        "China 240-hour visa-free transit",
        "China transit without visa",
        "China TWOV rules",
        "China stopover itinerary",
      ],
      ogImage: journalImages.visaFreeTransit,
    },
    related: {
      destinations: ["beijing", "shanghai"],
      tours: ["first-china-beautifully-paced"],
    },
    sourcePath: "content/journal/articles/2026-08-06-china-240-hour-visa-free-transit-guide.md",
  },
  {
    slug: "china-accommodation-registration-foreigners",
    title: "China Accommodation Registration for Foreign Visitors",
    dek: "Understand hotel registration, private-home stays and the current online pilot before arriving in China.",
    excerpt:
      "What foreign visitors need to know about China’s accommodation registration rules for hotels, apartments and private homes.",
    category: "Travel Guides",
    tags: ["first-time-china", "private-guides"],
    author,
    publishedAt: "2026-08-06",
    readingTime: "8 min read",
    hero: { eyebrow: "Arrival essentials", image: journalImages.accommodationRegistration },
    gallery: [journalImages.accommodationRegistration, destinationAsset.shanghaiSkyline],
    content: [],
    seo: {
      title: "China Accommodation Registration for Foreigners",
      description:
        "Understand China’s 24-hour accommodation registration rule, hotel handling and the 2026 online pilot for private-home stays before you arrive.",
      keywords: [
        "China accommodation registration for foreigners",
        "China temporary residence registration tourist",
        "register stay in China private apartment",
      ],
      ogImage: journalImages.accommodationRegistration,
    },
    sourcePath:
      "content/journal/articles/2026-08-06-china-accommodation-registration-foreigners.md",
  },
  {
    slug: "china-high-speed-train-foreigners",
    title: "China High-Speed Trains: A Passport-to-Platform Guide",
    dek: "Book, enter and board China’s high-speed trains with the right passport details, timing and seat choice.",
    excerpt:
      "A practical guide to China high-speed rail covering passport booking, e-tickets, stations, seats, baggage and missed trains.",
    category: "Train Travel",
    tags: ["train-travel", "first-time-china", "family-travel"],
    author,
    publishedAt: "2026-08-06",
    readingTime: "9 min read",
    hero: { eyebrow: "Rail planning", image: journalImages.highSpeedTrain },
    gallery: [journalImages.highSpeedTrain, destinationAsset.shanghaiSkyline],
    content: [],
    seo: {
      title: "China High-Speed Train Guide for Foreigners",
      description:
        "Book and board China high-speed trains with a passport, understand e-tickets, seat choices, baggage rules and station timing with confidence.",
      keywords: [
        "China high-speed train for foreigners",
        "China train passport booking",
        "China Railway 12306 foreign passport",
        "China train baggage rules",
      ],
      ogImage: journalImages.highSpeedTrain,
    },
    related: {
      destinations: ["beijing", "shanghai"],
      tours: ["first-china-beautifully-paced"],
      experiences: ["train-travel"],
    },
    sourcePath: "content/journal/articles/2026-08-06-china-high-speed-train-foreigners.md",
  },
  {
    slug: "china-mobile-payments-foreign-tourists",
    title: "Mobile Payments in China: A Visitor’s Setup Guide",
    dek: "Set up a mobile wallet with an overseas card and keep reliable card and cash backups for your trip.",
    excerpt:
      "How international visitors can prepare mobile payments, overseas cards and RMB cash before traveling in China.",
    category: "Travel Guides",
    tags: ["first-time-china", "family-travel", "train-travel"],
    author,
    publishedAt: "2026-08-06",
    readingTime: "9 min read",
    hero: { eyebrow: "Practical planning", image: journalImages.mobilePayment },
    gallery: [journalImages.mobilePayment, destinationAsset.chengduTeaHouse],
    content: [],
    seo: {
      title: "China Mobile Payments for Tourists: Setup Guide",
      description:
        "Set up Alipay or Weixin Pay with an overseas card, keep reliable backups and know where cash or cards still matter on a China trip.",
      keywords: [
        "China mobile payment for tourists",
        "Alipay for foreigners",
        "WeChat Pay overseas card",
        "paying in China as a tourist",
      ],
      ogImage: journalImages.mobilePayment,
    },
    sourcePath: "content/journal/articles/2026-08-06-china-mobile-payments-foreign-tourists.md",
  },
  {
    slug: "forbidden-city-tickets-foreigners",
    title: "Forbidden City Tickets for Foreign Visitors",
    dek: "Reserve with the correct passport, avoid same-day and Monday mistakes, and plan a realistic Palace Museum visit.",
    excerpt:
      "A clear booking and visit guide for foreign passport holders planning the Forbidden City in Beijing.",
    category: "Destinations",
    tags: ["beijing", "first-time-china", "private-guides"],
    author,
    publishedAt: "2026-08-06",
    readingTime: "8 min read",
    hero: { eyebrow: "Beijing planning", image: journalImages.forbiddenCityEntrance },
    gallery: [journalImages.forbiddenCityEntrance, destinationAsset.beijingForbiddenCityWide],
    content: [],
    seo: {
      title: "Forbidden City Tickets for Foreigners: 2026 Guide",
      description:
        "Reserve Forbidden City tickets with a passport, avoid same-day and Monday mistakes, and plan a well-paced Palace Museum visit before Beijing.",
      keywords: [
        "Forbidden City tickets for foreigners",
        "Palace Museum tickets passport",
        "Forbidden City advance booking",
        "Forbidden City closed Monday",
      ],
      ogImage: journalImages.forbiddenCityEntrance,
    },
    related: {
      destinations: ["beijing"],
      tours: ["beijing-great-wall-private-5-day-tour", "first-china-beautifully-paced"],
    },
    sourcePath: "content/journal/articles/2026-08-06-forbidden-city-tickets-foreigners.md",
  },
  {
    slug: "chengdu-panda-base-tickets-foreigners",
    title: "Chengdu Panda Base Tickets for Foreign Visitors",
    dek: "Reserve with the correct passport, choose a workable entry window and plan a cooler, calmer morning at Chengdu Panda Base.",
    excerpt:
      "How foreign visitors can reserve Chengdu Panda Base tickets, choose an entry window and plan a comfortable half-day visit.",
    category: "Family Travel",
    tags: ["chengdu", "pandas", "family-travel", "first-time-china"],
    author,
    publishedAt: "2026-08-08",
    readingTime: "9 min read",
    editorPick: true,
    hero: { eyebrow: "Chengdu planning", image: journalImages.chengduPandaBase },
    gallery: [journalImages.chengduPandasPlatform, journalImages.chengduPandaClose],
    content: [],
    seo: {
      title: "Chengdu Panda Base Tickets: 2026 Visitor Guide",
      description:
        "Learn how foreign visitors reserve Chengdu Panda Base tickets, choose an entry window and plan a cooler, calmer morning visit.",
      keywords: [
        "Chengdu Panda Base tickets for foreigners",
        "Chengdu Research Base ticket reservation",
        "Chengdu panda tickets passport",
        "Chengdu Panda Base opening hours",
        "Chengdu panda visit morning",
      ],
      ogImage: journalImages.chengduPandaBase,
    },
    related: {
      destinations: ["chengdu"],
      tours: ["chengdu-pandas-sichuan-table"],
      articles: ["china-high-speed-train-foreigners"],
    },
    sourcePath: "content/journal/articles/2026-08-07-chengdu-panda-base-tickets-foreigners.md",
  },
  {
    slug: "china-sim-card-esim-internet-foreign-tourists",
    title: "China SIM Cards and Mobile Data for Foreign Visitors",
    dek: "Compare roaming, travel eSIMs and local SIM cards, then keep a practical backup for maps, payments and arrival contacts.",
    excerpt:
      "A practical comparison of roaming, eSIM and local SIM options for international visitors who need dependable mobile data in China.",
    category: "Travel Guides",
    tags: ["first-time-china", "beijing", "shanghai", "chengdu"],
    author,
    publishedAt: "2026-08-08",
    readingTime: "8 min read",
    hero: { eyebrow: "Connectivity planning", image: journalImages.simCardAirport },
    gallery: [journalImages.simCardCounter, journalImages.simCardPlanBoard],
    content: [],
    seo: {
      title: "China SIM Card and eSIM Guide for Tourists 2026",
      description:
        "Compare China SIM, roaming and eSIM preparation for foreign visitors, with a practical backup plan for maps, payments and hotel contact.",
      keywords: [
        "China SIM card for tourists",
        "China eSIM for foreign visitors",
        "mobile data in China",
        "China roaming travel",
        "China internet for tourists",
      ],
      ogImage: journalImages.simCardAirport,
    },
    related: {
      destinations: ["beijing", "shanghai", "chengdu"],
      articles: ["china-mobile-payments-foreign-tourists"],
    },
    sourcePath:
      "content/journal/articles/2026-08-07-china-sim-card-esim-internet-foreign-tourists.md",
  },
  {
    slug: "shanghai-pudong-hongqiao-airport-guide",
    title: "Shanghai Pudong or Hongqiao Airport: A Visitor Guide",
    dek: "Confirm PVG or SHA, compare onward transfers and choose the hotel location only after the correct airport is known.",
    excerpt:
      "A clear comparison of Shanghai Pudong and Hongqiao airports for international arrivals, hotel transfers and onward rail connections.",
    category: "Travel Guides",
    tags: ["shanghai", "first-time-china", "private-guides"],
    author,
    publishedAt: "2026-08-08",
    readingTime: "8 min read",
    hero: { eyebrow: "Shanghai arrival", image: journalImages.shanghaiAirportGuide },
    gallery: [],
    content: [],
    seo: {
      title: "Pudong or Hongqiao Airport? Shanghai Arrival Guide",
      description:
        "Understand Shanghai Pudong and Hongqiao airports, transfer choices and hotel details before arranging a first private China arrival.",
      keywords: [
        "Pudong or Hongqiao airport",
        "Shanghai airports for tourists",
        "Shanghai airport transfer",
        "PVG vs SHA",
        "Shanghai arrival planning",
      ],
      ogImage: journalImages.shanghaiAirportGuide,
    },
    related: {
      destinations: ["shanghai"],
      tours: ["first-china-beautifully-paced", "shanghai-zhangjiajie-floating-peaks"],
      articles: ["china-sim-card-esim-internet-foreign-tourists"],
    },
    sourcePath: "content/journal/articles/2026-08-07-shanghai-pudong-hongqiao-airport-guide.md",
  },
  {
    slug: "china-golden-week-travel-2026",
    title: "China’s 2026 Golden Week: Should You Travel?",
    dek: "Use the official October 1–7 dates to decide whether to keep, shift or redesign a private China itinerary.",
    excerpt:
      "A decision guide to China’s 2026 National Day holiday, covering route timing, transport, hotels and capacity-controlled attractions.",
    category: "Travel Guides",
    tags: ["autumn", "first-time-china", "train-travel"],
    author,
    publishedAt: "2026-08-08",
    readingTime: "9 min read",
    featured: true,
    hero: { eyebrow: "Seasonal planning", image: journalImages.goldenWeekRail },
    gallery: [journalImages.goldenWeekRailPortrait],
    content: [],
    seo: {
      title: "China Golden Week 2026: Dates and Travel Strategy",
      description:
        "China’s 2026 National Day holiday runs October 1–7. Decide whether to travel, what to reserve early and how to protect a private itinerary.",
      keywords: [
        "China Golden Week 2026",
        "China National Day holiday 2026",
        "travel China October 2026",
        "China Golden Week crowds",
        "China October holiday dates",
      ],
      ogImage: journalImages.goldenWeekRail,
    },
    related: {
      tours: ["first-china-beautifully-paced"],
      articles: ["china-high-speed-train-foreigners"],
      experiences: ["train-travel"],
    },
    sourcePath: "content/journal/articles/2026-08-08-china-golden-week-travel-2026.md",
  },
  {
    slug: "mutianyu-badaling-jinshanling-great-wall",
    title: "Mutianyu, Badaling or Jinshanling: Which Great Wall Section?",
    dek: "Compare access, walking load, crowd patterns and photography priorities before choosing a Great Wall day from Beijing.",
    excerpt:
      "A practical comparison of Mutianyu, Badaling and Jinshanling for travelers choosing the right Great Wall section from Beijing.",
    category: "Destinations",
    tags: ["beijing", "private-guides", "luxury-travel"],
    author,
    publishedAt: "2026-08-08",
    readingTime: "10 min read",
    editorPick: true,
    hero: { eyebrow: "Beijing day trip", image: journalImages.greatWallComparison },
    gallery: [journalImages.greatWallOverview],
    content: [],
    seo: {
      title: "Mutianyu vs Badaling vs Jinshanling Great Wall",
      description:
        "Compare Mutianyu, Badaling and Jinshanling by access, walking load, scenery and travel time to choose the right Great Wall section from Beijing.",
      keywords: [
        "Mutianyu vs Badaling vs Jinshanling",
        "best Great Wall section from Beijing",
        "Mutianyu or Badaling",
        "Jinshanling Great Wall day trip",
        "Great Wall for seniors",
      ],
      ogImage: journalImages.greatWallComparison,
    },
    related: {
      destinations: ["beijing"],
      tours: ["beijing-great-wall-private-5-day-tour", "first-china-beautifully-paced"],
      articles: ["forbidden-city-tickets-foreigners"],
    },
    sourcePath: "content/journal/articles/2026-08-08-mutianyu-badaling-jinshanling-great-wall.md",
  },
  {
    slug: "terracotta-army-tickets-foreign-visitors",
    title: "Terracotta Army Tickets for Foreign Visitors",
    dek: "Reserve with the correct passport, use the current entrance instructions and protect enough time for a dedicated Xi’an half-day.",
    excerpt:
      "A passport booking and visit guide for foreign visitors planning the Terracotta Army from central Xi’an.",
    category: "History",
    tags: ["xian", "first-time-china", "private-guides"],
    author,
    publishedAt: "2026-08-08",
    readingTime: "9 min read",
    editorPick: true,
    hero: { eyebrow: "Xi’an planning", image: journalImages.terracottaArmy },
    gallery: [journalImages.terracottaPortrait],
    content: [],
    seo: {
      title: "Terracotta Army Tickets for Foreign Visitors 2026",
      description:
        "Reserve Terracotta Army tickets with a passport, use the correct entrance and allow time for both museum areas on a well-planned Xi’an visit.",
      keywords: [
        "Terracotta Army tickets for foreigners",
        "Terracotta Warriors ticket passport",
        "Qin Shi Huang Mausoleum Museum booking",
        "Terracotta Army opening hours 2026",
        "Xi'an Terracotta Army visit",
      ],
      ogImage: journalImages.terracottaArmy,
    },
    related: {
      destinations: ["xian"],
      tours: [
        "first-china-beautifully-paced",
        "xian-beijing-terracotta-warriors-great-wall-private-6-day-tour",
      ],
      articles: ["china-high-speed-train-foreigners"],
    },
    sourcePath: "content/journal/articles/2026-08-08-terracotta-army-tickets-foreign-visitors.md",
  },
  {
    slug: "china-domestic-flight-power-bank-rules",
    title: "China Domestic Flight Power Bank Rules for Visitors",
    dek: "Check the physical CCC mark, readable capacity label, recall status and carry-on rules before a mainland domestic flight.",
    excerpt:
      "What international visitors need to check before taking a power bank through security for a domestic flight in mainland China.",
    category: "Travel Guides",
    tags: ["first-time-china", "family-travel"],
    author,
    publishedAt: "2026-08-08",
    readingTime: "9 min read",
    hero: { eyebrow: "Domestic flight rules", image: journalImages.powerBank },
    gallery: [journalImages.powerBankCarryOn],
    content: [],
    seo: {
      title: "China Power Bank Rules for Domestic Flights 2026",
      description:
        "Check China’s CCC-label rule, watt-hour rating, carry-on limits and recalled-model restrictions before taking a mainland domestic flight in 2026.",
      keywords: [
        "China domestic flight power bank rules",
        "China 3C power bank rule",
        "CCC power bank China airport",
        "power bank China domestic flight",
        "China airline battery rules",
      ],
      ogImage: journalImages.powerBank,
    },
    related: {
      tours: ["shanghai-zhangjiajie-floating-peaks"],
      articles: ["shanghai-pudong-hongqiao-airport-guide"],
    },
    sourcePath: "content/journal/articles/2026-08-08-china-domestic-flight-power-bank-rules.md",
  },
  {
    slug: "bringing-prescription-medicine-to-china",
    title: "Bringing Prescription Medicine to China: A Visitor Checklist",
    dek: "Check active ingredients, prepare supporting documents and carry a reasonable personal supply in clearly labeled original packaging.",
    excerpt:
      "A documentation and packing checklist for international visitors bringing prescription medicine through China Customs.",
    category: "Travel Guides",
    tags: ["first-time-china", "family-travel"],
    author,
    publishedAt: "2026-08-08",
    readingTime: "10 min read",
    hero: { eyebrow: "Health planning", image: journalImages.medicine },
    gallery: [journalImages.medicinePackaging, journalImages.medicineList],
    content: [],
    seo: {
      title: "Bringing Prescription Medicine to China: Guide",
      description:
        "Prepare prescriptions, original packaging and supporting documents before carrying personal medicine through China Customs as an international visitor.",
      keywords: [
        "bringing prescription medicine to China",
        "China customs medication rules",
        "travel to China with medicine",
        "psychotropic medicine China entry",
        "prescription letter China travel",
      ],
      ogImage: journalImages.medicine,
    },
    related: {
      tours: ["first-china-beautifully-paced"],
      articles: ["china-accommodation-registration-foreigners"],
    },
    sourcePath: "content/journal/articles/2026-08-08-bringing-prescription-medicine-to-china.md",
  },
];
