import { destinationAsset } from "@/content/destinations/assets";
import { homeEditorialImages } from "@/content/home/homepage";
import type { JournalArticle } from "@/types/journal";

const author = {
  name: "AVIORA Travel Team",
  role: "China travel specialists",
};

const journalImages = {
  visaFreeTransit: {
    src: "/journal/2026-08-06/visa-free-transit-shanghai.webp",
    alt: "International visitors on the Bund with the Shanghai skyline behind them",
    width: 1620,
    height: 1080,
    objectPosition: "50% 52%",
  },
  accommodationRegistration: {
    src: "/journal/2026-08-06/accommodation-registration-check-in.webp",
    alt: "International guests with hotel staff at a reception in China",
    width: 1706,
    height: 1279,
    objectPosition: "50% 58%",
  },
  highSpeedTrain: {
    src: "/journal/2026-08-06/china-high-speed-train-boarding.webp",
    alt: "International traveler beside a high-speed train platform in China",
    width: 2400,
    height: 3200,
    objectPosition: "50% 48%",
  },
  mobilePayment: {
    src: "/journal/2026-08-06/china-mobile-payment.webp",
    alt: "Traveler completing a mobile payment at a counter in China",
    width: 2400,
    height: 3200,
    objectPosition: "50% 57%",
  },
  forbiddenCityEntrance: {
    src: "/journal/2026-08-06/forbidden-city-entrance.webp",
    alt: "Bronze guardian lion at the entrance to the Forbidden City in Beijing",
    width: 2400,
    height: 3199,
    objectPosition: "64% 60%",
  },
  chengduPandaBase: {
    src: "/journal/2026-08-07/chengdu-panda-base-hero.webp",
    alt: "Two giant pandas resting and feeding on wooden platforms at Chengdu Panda Base",
    width: 1800,
    height: 1200,
    objectPosition: "50% 48%",
  },
  chengduPandasPlatform: {
    src: "/journal/2026-08-07/chengdu-pandas-platform.webp",
    alt: "Two giant pandas resting and feeding on wooden platforms at Chengdu Panda Base",
    width: 1200,
    height: 1600,
    objectPosition: "50% 48%",
  },
  chengduPandaClose: {
    src: "/journal/2026-08-07/chengdu-panda-close-view.webp",
    alt: "A giant panda walking through a wooded enclosure at Chengdu Panda Base",
    width: 1200,
    height: 1600,
    objectPosition: "50% 52%",
  },
  simCardAirport: {
    src: "/journal/2026-08-07/china-sim-card-airport-counter-hero.webp",
    alt: "China Unicom tourist SIM card counter at Beijing Daxing International Airport",
    width: 1800,
    height: 1200,
    objectPosition: "50% 48%",
  },
  simCardCounter: {
    src: "/journal/2026-08-07/china-sim-card-airport-counter.webp",
    alt: "China Unicom tourist SIM card counter at Beijing Daxing International Airport",
    width: 1200,
    height: 1600,
    objectPosition: "50% 48%",
  },
  simCardPlanBoard: {
    src: "/journal/2026-08-07/china-unicom-tourist-sim-plan-board.webp",
    alt: "Printed China Unicom tourist SIM plan board at Beijing Daxing International Airport",
    width: 1200,
    height: 1600,
    objectPosition: "50% 52%",
  },
  shanghaiAirportGuide: {
    src: "/home/shanghai-pudong-skyline.webp",
    alt: "Shanghai Pudong skyline seen across the Huangpu River",
    width: 1920,
    height: 1080,
    objectPosition: "50% 45%",
  },
  goldenWeekRail: {
    src: "/journal/2026-08-08/china-golden-week-high-speed-rail-hero.webp",
    alt: "Fuxing high-speed trains lined up at Shenzhen North Railway Station",
    width: 1800,
    height: 1200,
    objectPosition: "50% 52%",
  },
  goldenWeekRailPortrait: {
    src: "/journal/2026-08-08/shenzhen-north-high-speed-trains.webp",
    alt: "Fuxing high-speed trains lined up at Shenzhen North Railway Station",
    width: 1200,
    height: 1803,
    objectPosition: "50% 50%",
  },
  greatWallComparison: {
    src: "/tours/beijing-unhurried/great-wall-walk.webp",
    alt: "Cable car beside Great Wall ramparts crossing a mountain ridge",
    width: 2400,
    height: 1641,
    objectPosition: "50% 48%",
  },
  greatWallOverview: {
    src: "/tours/beijing-unhurried/great-wall-overview.webp",
    alt: "Great Wall ramparts crossing forested mountains near Beijing",
    width: 864,
    height: 1488,
    objectPosition: "50% 46%",
  },
  terracottaArmy: {
    src: "/home/xian-terracotta-army.webp",
    alt: "Rows of terracotta warriors inside the Qin Shi Huang Mausoleum Museum",
    width: 1400,
    height: 927,
    objectPosition: "50% 48%",
  },
  terracottaPortrait: {
    src: "/tours/first-china-beautifully-paced/xian-terracotta-army-portrait.webp",
    alt: "Individual terracotta warrior showing detailed armor and facial features",
    width: 1440,
    height: 1920,
    objectPosition: "50% 45%",
  },
  powerBank: {
    src: "/journal/2026-08-08/china-domestic-flight-power-bank-hero.webp",
    alt: "Power bank and charging cable inside a passenger's carry-on bag",
    width: 1800,
    height: 1200,
    objectPosition: "50% 50%",
  },
  powerBankCarryOn: {
    src: "/journal/2026-08-08/power-bank-in-carry-on-bag.webp",
    alt: "Power bank and charging cable inside a passenger's carry-on bag",
    width: 1200,
    height: 1600,
    objectPosition: "50% 50%",
  },
  medicine: {
    src: "/journal/2026-08-08/bringing-medicine-to-china-hero.webp",
    alt: "Several medicines kept in their labeled original packaging for travel",
    width: 1800,
    height: 1200,
    objectPosition: "50% 50%",
  },
  medicinePackaging: {
    src: "/journal/2026-08-08/medicine-in-original-packaging.webp",
    alt: "Several medicines kept in their labeled original packaging for travel",
    width: 1200,
    height: 1600,
    objectPosition: "50% 50%",
  },
  medicineList: {
    src: "/journal/2026-08-08/personal-medicine-declaration-list.webp",
    alt: "Example bilingual personal medicine declaration list",
    width: 1200,
    height: 1600,
    objectPosition: "50% 46%",
  },
} as const;

export const publishedJournalArticles: JournalArticle[] = [
  {
    slug: "aviora-ttg-asia-matta-connect-2026",
    title: "Listening Before Designing: AVIORA at MATTA Connect",
    dek: "TTG Asia named Guohui Shi of China Prime DMC, AVIORA's China operating team, in its MATTA Connect 2026 coverage. The more important story is why listening comes before itinerary design.",
    excerpt:
      "How AVIORA turns conversations with Malaysian travel buyers into clearer, more considerate private journeys through China.",
    category: "Industry News",
    tags: ["travel-trade", "malaysia", "muslim-friendly", "private-guides"],
    author,
    publishedAt: "2026-08-08",
    readingTime: "6 min read",
    featured: true,
    editorPick: true,
    hero: {
      eyebrow: "AVIORA in the travel trade",
      image: homeEditorialImages.tradeBuyerMeeting,
    },
    gallery: [homeEditorialImages.tradeMuslimBuyers, homeEditorialImages.tradeConsultation],
    content: [],
    seo: {
      title: "AVIORA at MATTA Connect | Featured in TTG Asia",
      description:
        "TTG Asia named Guohui Shi of AVIORA's China operating team in its MATTA Connect coverage. Read how listening shapes more thoughtful private China journeys.",
      keywords: [
        "AVIORA MATTA Connect",
        "AVIORA private China travel",
        "China Prime DMC TTG Asia",
        "China Prime DMC MATTA Connect",
        "Guohui Shi China Prime DMC",
        "China inbound travel specialist",
        "Malaysia China private travel",
      ],
      ogImage: homeEditorialImages.tradeBuyerMeeting,
    },
    related: {
      tours: [
        "first-china-beautifully-paced",
        "chengdu-pandas-jiuzhaigou-private-7-day-tour",
        "xian-beijing-terracotta-warriors-great-wall-private-6-day-tour",
      ],
      articles: ["china-240-hour-visa-free-transit-guide", "china-high-speed-train-foreigners"],
    },
    citations: [
      {
        name: "MATTA Connect gains traction as B2B platform",
        url: "https://www.ttgasia.com/2026/07/30/matta-connect-gains-traction-as-b2b-platform/",
        publisher: "TTG Asia",
        publishedAt: "2026-07-30",
      },
    ],
    sourcePath: "content/journal/articles/2026-08-08-china-prime-dmc-ttg-asia-matta-connect.md",
  },
  {
    slug: "china-240-hour-visa-free-transit-guide",
    title: "China’s 240-Hour Visa-Free Transit: A Route-First Guide",
    dek: "Check nationality, ports, onward routing and permitted areas before building a visa-free China stopover.",
    excerpt:
      "A route-first explanation of China’s 240-hour transit policy for travelers planning Beijing, Shanghai or another eligible stopover.",
    category: "Visa",
    tags: ["first-time-china", "beijing", "shanghai", "private-guides"],
    author,
    publishedAt: "2026-08-06",
    readingTime: "10 min read",
    hero: { eyebrow: "Entry planning", image: journalImages.visaFreeTransit },
    gallery: [journalImages.visaFreeTransit, destinationAsset.beijingForbiddenCityWide],
    content: [],
    seo: {
      title: "China 240-Hour Visa-Free Transit Guide 2026",
      description:
        "Check China’s 240-hour visa-free transit rules, eligible routes, ports and permitted areas before building a Beijing or Shanghai stopover.",
      keywords: [
        "China 240-hour visa-free transit",
        "China transit without visa",
        "China TWOV rules",
        "China stopover itinerary",
      ],
      ogImage: journalImages.visaFreeTransit,
    },
    related: {
      destinations: ["beijing", "shanghai"],
      tours: ["first-china-beautifully-paced"],
    },
    sourcePath: "content/journal/articles/2026-08-06-china-240-hour-visa-free-transit-guide.md",
  },
  {
    slug: "china-accommodation-registration-foreigners",
    title: "China Accommodation Registration for Foreign Visitors",
    dek: "Understand hotel registration, private-home stays and the current online pilot before arriving in China.",
    excerpt:
      "What foreign visitors need to know about China’s accommodation registration rules for hotels, apartments and private homes.",
    category: "Travel Guides",
    tags: ["first-time-china", "private-guides"],
    author,
    publishedAt: "2026-08-06",
    readingTime: "8 min read",
    hero: { eyebrow: "Arrival essentials", image: journalImages.accommodationRegistration },
    gallery: [journalImages.accommodationRegistration, destinationAsset.shanghaiSkyline],
    content: [],
    seo: {
      title: "China Accommodation Registration for Foreigners",
      description:
        "Understand China’s 24-hour accommodation registration rule, hotel handling and the 2026 online pilot for private-home stays before you arrive.",
      keywords: [
        "China accommodation registration for foreigners",
        "China temporary residence registration tourist",
        "register stay in China private apartment",
      ],
      ogImage: journalImages.accommodationRegistration,
    },
    sourcePath:
      "content/journal/articles/2026-08-06-china-accommodation-registration-foreigners.md",
  },
  {
    slug: "china-high-speed-train-foreigners",
    title: "China High-Speed Trains: A Passport-to-Platform Guide",
    dek: "Book, enter and board China’s high-speed trains with the right passport details, timing and seat choice.",
    excerpt:
      "A practical guide to China high-speed rail covering passport booking, e-tickets, stations, seats, baggage and missed trains.",
    category: "Train Travel",
    tags: ["train-travel", "first-time-china", "family-travel"],
    author,
    publishedAt: "2026-08-06",
    readingTime: "9 min read",
    hero: { eyebrow: "Rail planning", image: journalImages.highSpeedTrain },
    gallery: [journalImages.highSpeedTrain, destinationAsset.shanghaiSkyline],
    content: [],
    seo: {
      title: "China High-Speed Train Guide for Foreigners",
      description:
        "Book and board China high-speed trains with a passport, understand e-tickets, seat choices, baggage rules and station timing with confidence.",
      keywords: [
        "China high-speed train for foreigners",
        "China train passport booking",
        "China Railway 12306 foreign passport",
        "China train baggage rules",
      ],
      ogImage: journalImages.highSpeedTrain,
    },
    related: {
      destinations: ["beijing", "shanghai"],
      tours: ["first-china-beautifully-paced"],
      experiences: ["train-travel"],
    },
    sourcePath: "content/journal/articles/2026-08-06-china-high-speed-train-foreigners.md",
  },
  {
    slug: "china-mobile-payments-foreign-tourists",
    title: "Mobile Payments in China: A Visitor’s Setup Guide",
    dek: "Set up a mobile wallet with an overseas card and keep reliable card and cash backups for your trip.",
    excerpt:
      "How international visitors can prepare mobile payments, overseas cards and RMB cash before traveling in China.",
    category: "Travel Guides",
    tags: ["first-time-china", "family-travel", "train-travel"],
    author,
    publishedAt: "2026-08-06",
    readingTime: "9 min read",
    hero: { eyebrow: "Practical planning", image: journalImages.mobilePayment },
    gallery: [journalImages.mobilePayment, destinationAsset.chengduTeaHouse],
    content: [],
    seo: {
      title: "China Mobile Payments for Tourists: Setup Guide",
      description:
        "Set up Alipay or Weixin Pay with an overseas card, keep reliable backups and know where cash or cards still matter on a China trip.",
      keywords: [
        "China mobile payment for tourists",
        "Alipay for foreigners",
        "WeChat Pay overseas card",
        "paying in China as a tourist",
      ],
      ogImage: journalImages.mobilePayment,
    },
    sourcePath: "content/journal/articles/2026-08-06-china-mobile-payments-foreign-tourists.md",
  },
  {
    slug: "forbidden-city-tickets-foreigners",
    title: "Forbidden City Tickets for Foreign Visitors",
    dek: "Reserve with the correct passport, avoid same-day and Monday mistakes, and plan a realistic Palace Museum visit.",
    excerpt:
      "A clear booking and visit guide for foreign passport holders planning the Forbidden City in Beijing.",
    category: "Destinations",
    tags: ["beijing", "first-time-china", "private-guides"],
    author,
    publishedAt: "2026-08-06",
    readingTime: "8 min read",
    hero: { eyebrow: "Beijing planning", image: journalImages.forbiddenCityEntrance },
    gallery: [journalImages.forbiddenCityEntrance, destinationAsset.beijingForbiddenCityWide],
    content: [],
    seo: {
      title: "Forbidden City Tickets for Foreigners: 2026 Guide",
      description:
        "Reserve Forbidden City tickets with a passport, avoid same-day and Monday mistakes, and plan a well-paced Palace Museum visit before Beijing.",
      keywords: [
        "Forbidden City tickets for foreigners",
        "Palace Museum tickets passport",
        "Forbidden City advance booking",
        "Forbidden City closed Monday",
      ],
      ogImage: journalImages.forbiddenCityEntrance,
    },
    related: {
      destinations: ["beijing"],
      tours: ["beijing-great-wall-private-5-day-tour", "first-china-beautifully-paced"],
    },
    sourcePath: "content/journal/articles/2026-08-06-forbidden-city-tickets-foreigners.md",
  },
  {
    slug: "chengdu-panda-base-tickets-foreigners",
    title: "Chengdu Panda Base Tickets for Foreign Visitors",
    dek: "Reserve with the correct passport, choose a workable entry window and plan a cooler, calmer morning at Chengdu Panda Base.",
    excerpt:
      "How foreign visitors can reserve Chengdu Panda Base tickets, choose an entry window and plan a comfortable half-day visit.",
    category: "Family Travel",
    tags: ["chengdu", "pandas", "family-travel", "first-time-china"],
    author,
    publishedAt: "2026-08-08",
    readingTime: "9 min read",
    editorPick: true,
    hero: { eyebrow: "Chengdu planning", image: journalImages.chengduPandaBase },
    gallery: [journalImages.chengduPandasPlatform, journalImages.chengduPandaClose],
    content: [],
    seo: {
      title: "Chengdu Panda Base Tickets: 2026 Visitor Guide",
      description:
        "Learn how foreign visitors reserve Chengdu Panda Base tickets, choose an entry window and plan a cooler, calmer morning visit.",
      keywords: [
        "Chengdu Panda Base tickets for foreigners",
        "Chengdu Research Base ticket reservation",
        "Chengdu panda tickets passport",
        "Chengdu Panda Base opening hours",
        "Chengdu panda visit morning",
      ],
      ogImage: journalImages.chengduPandaBase,
    },
    related: {
      destinations: ["chengdu"],
      tours: ["chengdu-pandas-sichuan-table"],
      articles: ["china-high-speed-train-foreigners"],
    },
    sourcePath: "content/journal/articles/2026-08-07-chengdu-panda-base-tickets-foreigners.md",
  },
  {
    slug: "china-sim-card-esim-internet-foreign-tourists",
    title: "China SIM Cards and Mobile Data for Foreign Visitors",
    dek: "Compare roaming, travel eSIMs and local SIM cards, then keep a practical backup for maps, payments and arrival contacts.",
    excerpt:
      "A practical comparison of roaming, eSIM and local SIM options for international visitors who need dependable mobile data in China.",
    category: "Travel Guides",
    tags: ["first-time-china", "beijing", "shanghai", "chengdu"],
    author,
    publishedAt: "2026-08-08",
    readingTime: "8 min read",
    hero: { eyebrow: "Connectivity planning", image: journalImages.simCardAirport },
    gallery: [journalImages.simCardCounter, journalImages.simCardPlanBoard],
    content: [],
    seo: {
      title: "China SIM Card and eSIM Guide for Tourists 2026",
      description:
        "Compare China SIM, roaming and eSIM preparation for foreign visitors, with a practical backup plan for maps, payments and hotel contact.",
      keywords: [
        "China SIM card for tourists",
        "China eSIM for foreign visitors",
        "mobile data in China",
        "China roaming travel",
        "China internet for tourists",
      ],
      ogImage: journalImages.simCardAirport,
    },
    related: {
      destinations: ["beijing", "shanghai", "chengdu"],
      articles: ["china-mobile-payments-foreign-tourists"],
    },
    sourcePath:
      "content/journal/articles/2026-08-07-china-sim-card-esim-internet-foreign-tourists.md",
  },
  {
    slug: "shanghai-pudong-hongqiao-airport-guide",
    title: "Shanghai Pudong or Hongqiao Airport: A Visitor Guide",
    dek: "Confirm PVG or SHA, compare onward transfers and choose the hotel location only after the correct airport is known.",
    excerpt:
      "A clear comparison of Shanghai Pudong and Hongqiao airports for international arrivals, hotel transfers and onward rail connections.",
    category: "Travel Guides",
    tags: ["shanghai", "first-time-china", "private-guides"],
    author,
    publishedAt: "2026-08-08",
    readingTime: "8 min read",
    hero: { eyebrow: "Shanghai arrival", image: journalImages.shanghaiAirportGuide },
    gallery: [],
    content: [],
    seo: {
      title: "Pudong or Hongqiao Airport? Shanghai Arrival Guide",
      description:
        "Understand Shanghai Pudong and Hongqiao airports, transfer choices and hotel details before arranging a first private China arrival.",
      keywords: [
        "Pudong or Hongqiao airport",
        "Shanghai airports for tourists",
        "Shanghai airport transfer",
        "PVG vs SHA",
        "Shanghai arrival planning",
      ],
      ogImage: journalImages.shanghaiAirportGuide,
    },
    related: {
      destinations: ["shanghai"],
      tours: ["first-china-beautifully-paced", "shanghai-zhangjiajie-floating-peaks"],
      articles: ["china-sim-card-esim-internet-foreign-tourists"],
    },
    sourcePath: "content/journal/articles/2026-08-07-shanghai-pudong-hongqiao-airport-guide.md",
  },
  {
    slug: "china-golden-week-travel-2026",
    title: "China’s 2026 Golden Week: Should You Travel?",
    dek: "Use the official October 1–7 dates to decide whether to keep, shift or redesign a private China itinerary.",
    excerpt:
      "A decision guide to China’s 2026 National Day holiday, covering route timing, transport, hotels and capacity-controlled attractions.",
    category: "Travel Guides",
    tags: ["autumn", "first-time-china", "train-travel"],
    author,
    publishedAt: "2026-08-08",
    readingTime: "9 min read",
    featured: true,
    hero: { eyebrow: "Seasonal planning", image: journalImages.goldenWeekRail },
    gallery: [journalImages.goldenWeekRailPortrait],
    content: [],
    seo: {
      title: "China Golden Week 2026: Dates and Travel Strategy",
      description:
        "China’s 2026 National Day holiday runs October 1–7. Decide whether to travel, what to reserve early and how to protect a private itinerary.",
      keywords: [
        "China Golden Week 2026",
        "China National Day holiday 2026",
        "travel China October 2026",
        "China Golden Week crowds",
        "China October holiday dates",
      ],
      ogImage: journalImages.goldenWeekRail,
    },
    related: {
      tours: ["first-china-beautifully-paced"],
      articles: ["china-high-speed-train-foreigners"],
      experiences: ["train-travel"],
    },
    sourcePath: "content/journal/articles/2026-08-08-china-golden-week-travel-2026.md",
  },
  {
    slug: "mutianyu-badaling-jinshanling-great-wall",
    title: "Mutianyu, Badaling or Jinshanling: Which Great Wall Section?",
    dek: "Compare access, walking load, crowd patterns and photography priorities before choosing a Great Wall day from Beijing.",
    excerpt:
      "A practical comparison of Mutianyu, Badaling and Jinshanling for travelers choosing the right Great Wall section from Beijing.",
    category: "Destinations",
    tags: ["beijing", "private-guides", "luxury-travel"],
    author,
    publishedAt: "2026-08-08",
    readingTime: "10 min read",
    editorPick: true,
    hero: { eyebrow: "Beijing day trip", image: journalImages.greatWallComparison },
    gallery: [journalImages.greatWallOverview],
    content: [],
    seo: {
      title: "Mutianyu vs Badaling vs Jinshanling Great Wall",
      description:
        "Compare Mutianyu, Badaling and Jinshanling by access, walking load, scenery and travel time to choose the right Great Wall section from Beijing.",
      keywords: [
        "Mutianyu vs Badaling vs Jinshanling",
        "best Great Wall section from Beijing",
        "Mutianyu or Badaling",
        "Jinshanling Great Wall day trip",
        "Great Wall for seniors",
      ],
      ogImage: journalImages.greatWallComparison,
    },
    related: {
      destinations: ["beijing"],
      tours: ["beijing-great-wall-private-5-day-tour", "first-china-beautifully-paced"],
      articles: ["forbidden-city-tickets-foreigners"],
    },
    sourcePath: "content/journal/articles/2026-08-08-mutianyu-badaling-jinshanling-great-wall.md",
  },
  {
    slug: "terracotta-army-tickets-foreign-visitors",
    title: "Terracotta Army Tickets for Foreign Visitors",
    dek: "Reserve with the correct passport, use the current entrance instructions and protect enough time for a dedicated Xi’an half-day.",
    excerpt:
      "A passport booking and visit guide for foreign visitors planning the Terracotta Army from central Xi’an.",
    category: "History",
    tags: ["xian", "first-time-china", "private-guides"],
    author,
    publishedAt: "2026-08-08",
    readingTime: "9 min read",
    editorPick: true,
    hero: { eyebrow: "Xi’an planning", image: journalImages.terracottaArmy },
    gallery: [journalImages.terracottaPortrait],
    content: [],
    seo: {
      title: "Terracotta Army Tickets for Foreign Visitors 2026",
      description:
        "Reserve Terracotta Army tickets with a passport, use the correct entrance and allow time for both museum areas on a well-planned Xi’an visit.",
      keywords: [
        "Terracotta Army tickets for foreigners",
        "Terracotta Warriors ticket passport",
        "Qin Shi Huang Mausoleum Museum booking",
        "Terracotta Army opening hours 2026",
        "Xi'an Terracotta Army visit",
      ],
      ogImage: journalImages.terracottaArmy,
    },
    related: {
      destinations: ["xian"],
      tours: [
        "first-china-beautifully-paced",
        "xian-beijing-terracotta-warriors-great-wall-private-6-day-tour",
      ],
      articles: ["china-high-speed-train-foreigners"],
    },
    sourcePath: "content/journal/articles/2026-08-08-terracotta-army-tickets-foreign-visitors.md",
  },
  {
    slug: "china-domestic-flight-power-bank-rules",
    title: "China Domestic Flight Power Bank Rules for Visitors",
    dek: "Check the physical CCC mark, readable capacity label, recall status and carry-on rules before a mainland domestic flight.",
    excerpt:
      "What international visitors need to check before taking a power bank through security for a domestic flight in mainland China.",
    category: "Travel Guides",
    tags: ["first-time-china", "family-travel"],
    author,
    publishedAt: "2026-08-08",
    readingTime: "9 min read",
    hero: { eyebrow: "Domestic flight rules", image: journalImages.powerBank },
    gallery: [journalImages.powerBankCarryOn],
    content: [],
    seo: {
      title: "China Power Bank Rules for Domestic Flights 2026",
      description:
        "Check China’s CCC-label rule, watt-hour rating, carry-on limits and recalled-model restrictions before taking a mainland domestic flight in 2026.",
      keywords: [
        "China domestic flight power bank rules",
        "China 3C power bank rule",
        "CCC power bank China airport",
        "power bank China domestic flight",
        "China airline battery rules",
      ],
      ogImage: journalImages.powerBank,
    },
    related: {
      tours: ["shanghai-zhangjiajie-floating-peaks"],
      articles: ["shanghai-pudong-hongqiao-airport-guide"],
    },
    sourcePath: "content/journal/articles/2026-08-08-china-domestic-flight-power-bank-rules.md",
  },
  {
    slug: "bringing-prescription-medicine-to-china",
    title: "Bringing Prescription Medicine to China: A Visitor Checklist",
    dek: "Check active ingredients, prepare supporting documents and carry a reasonable personal supply in clearly labeled original packaging.",
    excerpt:
      "A documentation and packing checklist for international visitors bringing prescription medicine through China Customs.",
    category: "Travel Guides",
    tags: ["first-time-china", "family-travel"],
    author,
    publishedAt: "2026-08-08",
    readingTime: "10 min read",
    hero: { eyebrow: "Health planning", image: journalImages.medicine },
    gallery: [journalImages.medicinePackaging, journalImages.medicineList],
    content: [],
    seo: {
      title: "Bringing Prescription Medicine to China: Guide",
      description:
        "Prepare prescriptions, original packaging and supporting documents before carrying personal medicine through China Customs as an international visitor.",
      keywords: [
        "bringing prescription medicine to China",
        "China customs medication rules",
        "travel to China with medicine",
        "psychotropic medicine China entry",
        "prescription letter China travel",
      ],
      ogImage: journalImages.medicine,
    },
    related: {
      tours: ["first-china-beautifully-paced"],
      articles: ["china-accommodation-registration-foreigners"],
    },
    sourcePath: "content/journal/articles/2026-08-08-bringing-prescription-medicine-to-china.md",
  },
];
