import type { MediaAsset } from "@/types/component-library";

const basePath = "/tours/beijing-xian-chengdu-shanghai-private-11-day-tour";

const galleryAlts = [
  "A spacious premium MPV interior prepared for a private China journey",
  "A cafe terrace overlooking Xi'an's historic Bell and Drum Tower area",
  "Shanghai's Bund, historic architecture and city traffic in warm evening light",
  "Xi'an's historic towers and city wall illuminated after dark",
  "Xi'an's traditional architecture glowing during an evening walk",
  "A bright Shanghai hotel room with a view toward the Pudong skyline",
  "A contemporary Xi'an hotel room overlooking the ancient city wall",
  "A traditional cultural performance beneath the trees in Chengdu",
  "Tea and refreshments served in Chengdu's People's Park",
  "China high-speed trains lined up inside a major railway station",
  "An imperial throne and historic interior detail inside Beijing's Forbidden City",
  "Sunlight passing through a restored palace doorway in Beijing's Forbidden City",
  "Decorative porcelain displayed inside a historic Beijing palace room",
  "A guardian lion and imperial architecture inside Beijing's Forbidden City",
  "A restored room inside the Hall of Mental Cultivation in Beijing",
  "An imperial bronze vessel against the red walls of Beijing's Forbidden City",
  "A photographer beside a glazed palace wall inside Beijing's Forbidden City",
  "An ornate imperial interior inside Beijing's Hall of Mental Cultivation",
  "A calm Beijing courtyard hotel room with garden light",
  "An intricately painted circular ceiling in a historic Beijing building",
  "A leafy tea-house garden in Chengdu's People's Park",
  "A forest-facing guest room in the mountains near Chengdu",
  "Shanghai's Customs House framed by the Pudong skyline at night",
  "A Tang-inspired cultural performance in Xi'an",
  "The Giant Wild Goose Pagoda and a historic Xi'an figure illuminated at night",
  "Lanterns and traditional architecture in Shanghai's Yu Garden district",
  "A spring lantern installation among the historic buildings of Shanghai's Yu Garden",
  "Traditional Shanghai architecture decorated for a seasonal Yu Garden festival",
  "The Hall of Prayer for Good Harvests beneath a clear Beijing sky",
  "Shanghai's Oriental Pearl Tower among the illuminated Pudong skyline",
  "An evening cruise passing Shanghai's historic waterfront and Pudong towers",
  "A wide dusk view of Shanghai's Pudong skyline across the Huangpu River",
  "Shanghai's skyline transitioning from daylight into evening",
  "Stone steps and watchtowers along the Mutianyu section of the Great Wall",
  "A Sichuan hotpot table prepared with regional ingredients in Chengdu",
  "Fresh ingredients and divided hotpot broths during a Chengdu food experience",
  "A group of giant pandas resting together at Chengdu Panda Base",
  "Giant pandas relaxing among the greenery at Chengdu Panda Base",
  "Sunbeams passing through bamboo along a path at Chengdu Panda Base",
  "Shanghai's Pudong skyline and Huangpu River at blue hour",
  "A sweeping aerial view across the Huangpu River and central Shanghai",
  "Shanghai's towers and riverfront illuminated beneath a pink evening sky",
  "Rows of Terracotta Warriors inside the main excavation hall near Xi'an",
  "A close view of an armored Terracotta Warrior near Xi'an",
  "Zhujiajiao water town and its arched bridges at sunset near Shanghai",
  "A waterside evening scene in Zhujiajiao near Shanghai",
  "A lively hotpot market and food scene in central Chengdu",
  "A Jiangnan-style meal beside the canals of Suzhou",
  "Suzhou's historic canals and waterside houses beneath a warm sunset",
  "A broad bamboo-lined walkway inside Chengdu Panda Base",
  "Two young giant pandas climbing a tree in Chengdu",
  "Rockeries, water and traditional architecture inside a Suzhou garden",
  "A quiet pavilion and pond inside a classical Suzhou garden",
  "International travelers sharing refreshments during a privately arranged China visit",
  "International guests relaxing inside a private touring vehicle in China",
  "Terracotta Warriors viewed across one of the excavation pits near Xi'an",
  "Terracotta Army figures standing in formation inside the museum near Xi'an",
  "Xi'an's ancient city wall beneath a dramatic red sunset",
  "A green garden and traditional pavilion inside Shanghai's Yu Garden",
  "Water, rockeries and historic architecture inside Shanghai's Yu Garden",
  "The detailed profile of a senior Terracotta Army officer near Xi'an",
  "Boats and historic buildings around Beijing's Shichahai lakes",
  "A traditional rickshaw traveling through a sunlit Beijing hutong",
  "A quiet tree-lined hutong lane in Beijing",
  "Historic residential architecture along a leafy Shanghai street",
  "A relaxed cafe terrace in Shanghai's former French Concession",
  "Curved historic architecture on a Shanghai neighborhood street",
  "Two older travelers enjoying the Great Wall near Beijing",
  "International travelers gathered together on the Great Wall near Beijing",
  "Shanghai Tower and the Pudong business district illuminated at night",
  "A private premium MPV with spacious reclining seats",
  "A modern premium cabin aboard a China high-speed train",
  "A wide reclining premium seat beside the window on a China high-speed train",
  "The Forbidden City and Beijing's historic central axis seen from above",
  "Shanghai's Customs House and Bund architecture illuminated beside the river",
  "The Bund and Pudong skyline illuminated across Shanghai's Huangpu River",
  "Shanghai's historic Customs House overlooking the Huangpu River",
] as const;

function photo(index: number, alt: string): MediaAsset {
  return {
    src: `${basePath}/photo-${String(index).padStart(2, "0")}.webp`,
    alt,
  };
}

export const fourCityGallery: MediaAsset[] = galleryAlts.map((alt, index) => photo(index + 1, alt));

function asset(index: number) {
  const image = fourCityGallery[index - 1];
  if (!image) throw new Error(`Missing four-city journey photo ${index}.`);
  return image;
}

export const fourCityAsset = {
  hero: { ...asset(42), priority: true, objectPosition: "50% 48%" },
  arrival: asset(19),
  beijingImperial: asset(74),
  greatWall: asset(69),
  rail: asset(72),
  xianTerracotta: asset(43),
  xianSunset: asset(58),
  chengduPandas: asset(37),
  shanghaiArrival: asset(32),
  shanghaiBund: asset(3),
  waterTown: asset(45),
  shanghaiDeparture: asset(77),
  pandaHighlight: asset(51),
  beijingHotel: asset(19),
  xianHotel: asset(7),
  chengduHotel: asset(22),
  shanghaiHotel: asset(6),
  familyTravel: asset(68),
  food: asset(35),
  finalDay: asset(46),
} satisfies Record<string, MediaAsset>;
