import type { MediaAsset } from "@/types/component-library";

export const destinationAsset = {
  forbiddenCityHero: {
    src: "/editorial/china-prime-dmc-home-forbidden-city-hero-2400.jpg",
    alt: "A majestic bright view over the Forbidden City in Beijing from Jingshan Park",
    width: 2400,
    height: 1200,
    objectPosition: "50% 42%",
  },
  lhasaPotalaPalace: {
    src: "/editorial/china-prime-dmc-lhasa-potala-palace-1800.jpg",
    alt: "Potala Palace in Lhasa, Tibet, under clear highland light",
    width: 1800,
    height: 706,
    objectPosition: "50% 45%",
  },
  xinjiangKanasLake: {
    src: "/editorial/china-prime-dmc-xinjiang-kanas-lake-1800.jpg",
    alt: "Kanas Lake in Xinjiang with bright alpine water and forested mountains",
    width: 1800,
    height: 1198,
    objectPosition: "50% 47%",
  },
  kashgarOldCity: {
    src: "/editorial/china-prime-dmc-kashgar-old-city-1800.jpg",
    alt: "Kashgar Old City in Xinjiang with warm traditional architecture",
    width: 1800,
    height: 1052,
    objectPosition: "50% 50%",
  },
  beijingForbiddenCity: {
    src: "/home/beijing-forbidden-city.jpg",
    alt: "The Forbidden City in Beijing at soft morning light",
    width: 1920,
    height: 1200,
    objectPosition: "50% 48%",
  },
  beijingForbiddenCityWide: {
    src: "/home/beijing-forbidden-city-1400.webp",
    alt: "Imperial palace roofs inside the Forbidden City in Beijing",
    width: 1400,
    height: 875,
    objectPosition: "50% 48%",
  },
  shanghaiSkyline: {
    src: "/home/shanghai-pudong-skyline.jpg",
    alt: "Shanghai Pudong skyline at dusk",
    width: 1920,
    height: 1080,
    objectPosition: "50% 45%",
  },
  chengduPanda: {
    src: "/home/chengdu-panda.jpg",
    alt: "A giant panda in Chengdu",
    width: 1920,
    height: 1200,
    objectPosition: "54% 42%",
  },
  chengduTeaHouse: {
    src: "/home/chengdu-tea-house.jpg",
    alt: "A traditional tea house experience in Chengdu",
    width: 1920,
    height: 1200,
    objectPosition: "50% 48%",
  },
  guilinRiver: {
    src: "/home/guilin-li-river.jpg",
    alt: "Li River karst scenery near Guilin",
    width: 1920,
    height: 1200,
    objectPosition: "50% 50%",
  },
  jiuzhaigouLake: {
    src: "/home/jiuzhaigou-five-flower-lake.jpg",
    alt: "Turquoise Five Flower Lake in Jiuzhaigou",
    width: 1920,
    height: 1200,
    objectPosition: "50% 44%",
  },
  xianTerracotta: {
    src: "/home/xian-terracotta-army.jpg",
    alt: "Terracotta Army figures in Xi'an",
    width: 1400,
    height: 927,
    objectPosition: "50% 48%",
  },
  yunnanLijiang: {
    src: "/home/yunnan-lijiang-old-town.webp",
    alt: "Traditional rooftops in Lijiang Old Town, Yunnan",
    width: 1400,
    height: 875,
    objectPosition: "50% 52%",
  },
  zhangjiajieForest: {
    src: "/home/zhangjiajie-national-forest.jpg",
    alt: "Sandstone pillar forest in Zhangjiajie",
    width: 1920,
    height: 1200,
    objectPosition: "52% 38%",
  },
  greatWallJinshanling: {
    src: "/journey-covers/first-china-family-private-tour-great-wall-jinshanling-1400.webp",
    alt: "Bright mountain ridges and the Great Wall at Jinshanling",
    width: 1400,
    height: 875,
    objectPosition: "50% 45%",
  },
  yangshuoYulongRiver: {
    src: "/journey-covers/china-honeymoon-yulong-river-yangshuo-1400.webp",
    alt: "Bright Yulong River scenery and karst mountains in Yangshuo",
    width: 1400,
    height: 875,
    objectPosition: "50% 50%",
  },
  jiuzhaigouBrightLake: {
    src: "/journey-covers/easy-pace-china-jiuzhaigou-five-flower-lake-1400.webp",
    alt: "Bright turquoise lake and autumn forest in Jiuzhaigou",
    width: 1400,
    height: 875,
    objectPosition: "50% 48%",
  },
  zhangjiajieAvatarPeaks: {
    src: "/journey-covers/china-avatar-peaks-zhangjiajie-national-forest-park-1400.webp",
    alt: "Dramatic sandstone peaks in Zhangjiajie National Forest Park",
    width: 1400,
    height: 875,
    objectPosition: "50% 42%",
  },
  westLakeSunset: {
    src: "/journey-covers/luxury-china-couples-hangzhou-west-lake-sunset-1400.webp",
    alt: "Warm sunset over West Lake in Hangzhou",
    width: 1400,
    height: 875,
    objectPosition: "50% 50%",
  },
  huangshanClouds: {
    src: "/journey-covers/shanghai-hangzhou-huangshan-yellow-mountain-clouds-1400.webp",
    alt: "Huangshan mountain peaks rising through bright clouds",
    width: 1400,
    height: 875,
    objectPosition: "50% 42%",
  },
  greatWallBright: {
    src: "/programs/beijing-great-wall-gubei-5-day/china-prime-dmc-beijing-great-wall-gubei-5-day-great-wall-of-china-1400.webp",
    alt: "Great Wall of China crossing green mountains in clear light",
    width: 1400,
    height: 933,
    objectPosition: "50% 45%",
  },
  liRiverBright: {
    src: "/programs/guangzhou-guilin-yangshuo-6-day/china-prime-dmc-guangzhou-guilin-yangshuo-6-day-li-river-1400.webp",
    alt: "Bright Li River scenery with karst mountains near Guilin",
    width: 1400,
    height: 933,
    objectPosition: "50% 50%",
  },
  templeOfHeaven: {
    src: "/programs/beijing-great-wall-gubei-5-day/china-prime-dmc-beijing-great-wall-gubei-5-day-temple-of-heaven-1400.webp",
    alt: "Temple of Heaven in Beijing under bright blue sky",
    width: 1400,
    height: 933,
    objectPosition: "50% 48%",
  },
  gubeiWaterTown: {
    src: "/programs/beijing-great-wall-gubei-5-day/china-prime-dmc-beijing-great-wall-gubei-5-day-gubei-water-town-1400.webp",
    alt: "Gubei Water Town near the Great Wall in warm light",
    width: 1400,
    height: 933,
    objectPosition: "50% 50%",
  },
  yuGarden: {
    src: "/programs/beijing-xian-shanghai-8-day/china-prime-dmc-beijing-xian-shanghai-8-day-yu-garden.jpg",
    alt: "Yu Garden in Shanghai with traditional architecture",
    width: 1280,
    height: 853,
    objectPosition: "50% 50%",
  },
  xianCityWall: {
    src: "/programs/classic-china-beijing-xian-shanghai-12-day/china-prime-dmc-classic-china-beijing-xian-shanghai-12-day-xi-an-city-wall.jpg",
    alt: "Xi'an city wall in clear daylight",
    width: 1280,
    height: 853,
    objectPosition: "50% 48%",
  },
  kuanzhaiAlley: {
    src: "/programs/chongqing-jiuzhaigou-chengdu-6-day/china-prime-dmc-chongqing-jiuzhaigou-chengdu-6-day-kuanzhai-alley.jpg",
    alt: "Kuanzhai Alley in Chengdu with local street atmosphere",
    width: 1280,
    height: 853,
    objectPosition: "50% 50%",
  },
  shanghaiTower: {
    src: "/programs/beijing-xian-shanghai-8-day/china-prime-dmc-beijing-xian-shanghai-8-day-shanghai-tower.jpg",
    alt: "Shanghai Tower and Pudong skyline in clear light",
    width: 1280,
    height: 853,
    objectPosition: "50% 45%",
  },
  goldenTriangleBeijing: {
    src: "/journey-covers/golden-triangle-forbidden-city-beijing-1400.webp",
    alt: "Bright imperial rooftops in Beijing on a classic China journey",
    width: 1400,
    height: 875,
    objectPosition: "50% 46%",
  },
  familyYangshuoCountryside: {
    src: "/journey-covers/china-with-kids-yangshuo-karst-countryside-1400.webp",
    alt: "Bright Yangshuo karst countryside for a family China journey",
    width: 1400,
    height: 875,
    objectPosition: "50% 48%",
  },
  familyChengduPanda: {
    src: "/journey-covers/family-china-panda-chengdu-private-tour-1400.webp",
    alt: "A giant panda in Chengdu on a family China journey",
    width: 1400,
    height: 875,
    objectPosition: "50% 44%",
  },
  shanghaiSuzhouGarden: {
    src: "/journey-covers/shanghai-suzhou-hangzhou-lingering-garden-1400.webp",
    alt: "Classical garden architecture in Suzhou for an elegant East China journey",
    width: 1400,
    height: 875,
    objectPosition: "50% 50%",
  },
  yunnanOldTown: {
    src: "/journey-covers/yunnan-slow-luxury-lijiang-old-town-1400.webp",
    alt: "Lijiang Old Town rooftops and mountain light in Yunnan",
    width: 1400,
    height: 875,
    objectPosition: "50% 50%",
  },
  silkRoadZhangye: {
    src: "/journey-covers/silk-road-desert-photography-zhangye-danxia-1400.webp",
    alt: "Rainbow mountains at Zhangye Danxia on the Silk Road",
    width: 1400,
    height: 875,
    objectPosition: "50% 48%",
  },
  silkRoadDunhuang: {
    src: "/programs/silk-road-gansu-ningxia-8-day/china-prime-dmc-silk-road-gansu-ningxia-8-day-crescent-lake-dunhuang-1400.webp",
    alt: "Crescent Lake and desert dunes in Dunhuang",
    width: 1400,
    height: 933,
    objectPosition: "50% 47%",
  },
  zhangyeDanxia: {
    src: "/programs/silk-road-gansu-ningxia-8-day/china-prime-dmc-silk-road-gansu-ningxia-8-day-zhangye-national-geopark-1400.webp",
    alt: "Zhangye National Geopark rainbow landforms in clear light",
    width: 1400,
    height: 933,
    objectPosition: "50% 48%",
  },
  daliOldTown: {
    src: "/programs/shangri-la-meili-snow-mountain-8-day/china-prime-dmc-shangri-la-meili-snow-mountain-8-day-dali-city-1400.webp",
    alt: "Dali old town and mountain scenery in Yunnan",
    width: 1400,
    height: 933,
    objectPosition: "50% 50%",
  },
  songzanlinMonastery: {
    src: "/programs/shangri-la-meili-snow-mountain-8-day/china-prime-dmc-shangri-la-meili-snow-mountain-8-day-songzanlin-monastery-1400.webp",
    alt: "Songzanlin Monastery near Shangri-La in Yunnan",
    width: 1400,
    height: 933,
    objectPosition: "50% 47%",
  },
  huanglongPools: {
    src: "/programs/sichuan-tibetan-nature-10-day/china-prime-dmc-sichuan-tibetan-nature-10-day-huanglong-scenic-and-historic-interest-area-1400.webp",
    alt: "Huanglong mineral pools in Sichuan mountain scenery",
    width: 1400,
    height: 933,
    objectPosition: "50% 48%",
  },
  jiuzhaigouValley: {
    src: "/programs/sichuan-tibetan-nature-10-day/china-prime-dmc-sichuan-tibetan-nature-10-day-jiuzhaigou-1400.webp",
    alt: "Jiuzhaigou valley lakes and forest in bright color",
    width: 1400,
    height: 933,
    objectPosition: "50% 47%",
  },
  tianmenMountain: {
    src: "/programs/zhangjiajie-fenghuang-5-day/china-prime-dmc-zhangjiajie-fenghuang-5-day-tianmen-mountain-1400.webp",
    alt: "Tianmen Mountain road and cliffs in Zhangjiajie",
    width: 1400,
    height: 933,
    objectPosition: "50% 44%",
  },
  zhangjiajieNationalForest: {
    src: "/programs/zhangjiajie-fenghuang-5-day/china-prime-dmc-zhangjiajie-fenghuang-5-day-zhangjiajie-national-forest-park-1400.webp",
    alt: "Zhangjiajie National Forest Park sandstone pillars",
    width: 1400,
    height: 933,
    objectPosition: "50% 42%",
  },
  chongqingHongyaCave: {
    src: "/programs/chongqing-chengdu-culture-food-5-day/china-prime-dmc-chongqing-chengdu-culture-food-5-day-hongya-cave-1400.webp",
    alt: "Hongya Cave and Chongqing riverside lights",
    width: 1400,
    height: 933,
    objectPosition: "50% 50%",
  },
  longjiRiceTerraces: {
    src: "/programs/guangzhou-guilin-yangshuo-6-day/china-prime-dmc-guangzhou-guilin-yangshuo-6-day-longji-rice-terraces-1400.webp",
    alt: "Longji rice terraces in Guangxi mountain scenery",
    width: 1400,
    height: 933,
    objectPosition: "50% 48%",
  },
  yangshuoCounty: {
    src: "/programs/guangzhou-guilin-yangshuo-6-day/china-prime-dmc-guangzhou-guilin-yangshuo-6-day-yangshuo-county-1400.webp",
    alt: "Yangshuo countryside and karst mountains in bright daylight",
    width: 1400,
    height: 933,
    objectPosition: "50% 48%",
  },
  shanghaiBund: {
    src: "/programs/shanghai-hangzhou-huangshan-9-day/china-prime-dmc-shanghai-hangzhou-huangshan-9-day-the-bund-1400.webp",
    alt: "The Bund and Shanghai skyline in clear evening light",
    width: 1400,
    height: 933,
    objectPosition: "50% 45%",
  },
  westLakeBright: {
    src: "/programs/shanghai-hangzhou-huangshan-9-day/china-prime-dmc-shanghai-hangzhou-huangshan-9-day-west-lake-1400.webp",
    alt: "West Lake in Hangzhou in calm bright light",
    width: 1400,
    height: 933,
    objectPosition: "50% 50%",
  },
  westLakeMultiGeneration: {
    src: "/journey-covers/multi-generation-china-west-lake-hangzhou-1400.webp",
    alt: "West Lake in Hangzhou for a slower multi-generation China journey",
    width: 1400,
    height: 875,
    objectPosition: "50% 50%",
  },
  xianGreatMosque: {
    src: "/journey-covers/muslim-friendly-classic-xian-great-mosque-1400.webp",
    alt: "Xi'an Great Mosque for a Muslim-friendly China heritage journey",
    width: 1400,
    height: 875,
    objectPosition: "50% 50%",
  },
  guilinElephantTrunkHill: {
    src: "/journey-covers/muslim-friendly-china-guilin-elephant-trunk-hill-1400.webp",
    alt: "Elephant Trunk Hill in Guilin for a Muslim-friendly classic China journey",
    width: 1400,
    height: 875,
    objectPosition: "50% 48%",
  },
  seniorTempleOfHeaven: {
    src: "/journey-covers/senior-friendly-classic-temple-of-heaven-beijing-1400.webp",
    alt: "Temple of Heaven in Beijing for a senior-friendly China journey",
    width: 1400,
    height: 875,
    objectPosition: "50% 48%",
  },
  leshanGiantBuddha: {
    src: "/journey-covers/panda-family-leshan-giant-buddha-sichuan-1400.webp",
    alt: "Leshan Giant Buddha in Sichuan on a family panda journey",
    width: 1400,
    height: 875,
    objectPosition: "50% 48%",
  },
  yangtzeQutangGorge: {
    src: "/journey-covers/yangtze-chengdu-classic-three-gorges-qutang-1400.webp",
    alt: "Qutang Gorge on the Yangtze River in China",
    width: 1400,
    height: 875,
    objectPosition: "50% 48%",
  },
  zhangjiajieGlassBridge: {
    src: "/journey-covers/teen-friendly-china-zhangjiajie-glass-bridge-1400.webp",
    alt: "Zhangjiajie glass bridge for a teen-friendly China adventure",
    width: 1400,
    height: 875,
    objectPosition: "50% 46%",
  },
  tianmenRoad: {
    src: "/journey-covers/beijing-xian-zhangjiajie-tianmen-mountain-road-1400.webp",
    alt: "Tianmen Mountain road in Zhangjiajie for an active China route",
    width: 1400,
    height: 875,
    objectPosition: "50% 46%",
  },
  meiliSnowMountain: {
    src: "/journey-covers/china-icons-landscapes-meili-snow-mountains-1400.webp",
    alt: "Meili Snow Mountain in Yunnan for a scenic China journey",
    width: 1400,
    height: 875,
    objectPosition: "50% 45%",
  },
  shanghaiDisneyCastle: {
    src: "/journey-covers/easy-china-children-shanghai-disneyland-castle-1400.webp",
    alt: "Shanghai Disneyland castle for an easy family China journey",
    width: 1400,
    height: 875,
    objectPosition: "50% 48%",
  },
  simataiGubeiWaterTown: {
    src: "/journey-covers/signature-heritage-gubei-water-town-simatai-1400.webp",
    alt: "Gubei Water Town and Simatai Great Wall near Beijing",
    width: 1400,
    height: 875,
    objectPosition: "50% 48%",
  },
  halalChengduPanda: {
    src: "/journey-covers/halal-aware-family-china-chengdu-panda-base-1400.webp",
    alt: "Chengdu panda base for a halal-aware family China journey",
    width: 1400,
    height: 875,
    objectPosition: "50% 45%",
  },
  longshengRiceTerraces: {
    src: "/journey-covers/family-soft-adventure-longsheng-rice-terraces-1400.webp",
    alt: "Longsheng rice terraces for a family soft-adventure China journey",
    width: 1400,
    height: 875,
    objectPosition: "50% 48%",
  },
} satisfies Record<string, MediaAsset>;
