import type { MediaAsset } from "@/types/component-library";

export const destinationAsset = {
  beijingForbiddenCity: {
    src: "/tours/first-china-beautifully-paced/beijing-great-wall-sunrise-hero.webp",
    alt: "The Great Wall crossing the mountains near Beijing in warm evening light",
    width: 1920,
    height: 1080,
    objectPosition: "50% 45%",
  },
  beijingForbiddenCityWide: {
    src: "/home/editorial/great-wall-private-china-travel.webp",
    alt: "A traveler looking across the Great Wall near Beijing",
    width: 1086,
    height: 1448,
    objectPosition: "50% 44%",
  },
  shanghaiSkyline: {
    src: "/home/shanghai-pudong-skyline.webp",
    alt: "Shanghai Pudong skyline at dusk",
    width: 1920,
    height: 1080,
    objectPosition: "50% 45%",
  },
  chengduPanda: {
    src: "/home/chengdu-panda.webp",
    alt: "A giant panda in Chengdu",
    width: 1920,
    height: 1200,
    objectPosition: "54% 42%",
  },
  chengduTeaHouse: {
    src: "/home/chengdu-tea-house.webp",
    alt: "A traditional tea house experience in Chengdu",
    width: 1920,
    height: 1200,
    objectPosition: "50% 48%",
  },
  guilinRiver: {
    src: "/home/guilin-li-river.webp",
    alt: "Li River karst scenery near Guilin",
    width: 1920,
    height: 1200,
    objectPosition: "50% 50%",
  },
  jiuzhaigouLake: {
    src: "/home/jiuzhaigou-five-flower-lake.webp",
    alt: "Turquoise Five Flower Lake in Jiuzhaigou",
    width: 1920,
    height: 1200,
    objectPosition: "50% 44%",
  },
  xianTerracotta: {
    src: "/home/xian-terracotta-army.webp",
    alt: "Terracotta Army figures in Xi'an",
    width: 1400,
    height: 927,
    objectPosition: "50% 48%",
  },
  yunnanLijiang: {
    src: "/home/yunnan-lijiang-old-town.webp",
    alt: "Traditional rooftops in Lijiang Old Town, Yunnan",
    width: 1400,
    height: 875,
    objectPosition: "50% 52%",
  },
  zhangjiajieForest: {
    src: "/home/zhangjiajie-national-forest.webp",
    alt: "Sandstone pillar forest in Zhangjiajie",
    width: 1920,
    height: 1200,
    objectPosition: "52% 38%",
  },
  zhangjiajieSpirePortrait: {
    src: "/home/zhangjiajie-sandstone-spire-portrait.jpg",
    alt: "Vertical sandstone spires in Zhangjiajie National Forest Park",
    width: 3376,
    height: 5064,
    objectPosition: "50% 44%",
  },
} satisfies Record<string, MediaAsset>;
