import { defineArrayMember, defineField, defineType } from "sanity";

import { commonGroups, portableTextField, seoFields } from "@/sanity/schemaTypes/shared";

export const blogPostType = defineType({
  name: "blogPost",
  title: "博客文章",
  type: "document",
  groups: commonGroups,
  fields: [
    defineField({
      name: "title",
      title: "文章标题",
      type: "string",
      group: "content",
      validation: (rule) => rule.required().min(8).max(120),
    }),
    defineField({
      name: "slug",
      title: "URL Slug",
      type: "slug",
      options: { source: "title", maxLength: 96 },
      group: "content",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "subtitle",
      title: "副标题",
      type: "text",
      rows: 2,
      group: "content",
      validation: (rule) => rule.required().min(20),
    }),
    defineField({
      name: "summary",
      title: "文章摘要",
      type: "text",
      rows: 3,
      group: "content",
      validation: (rule) => rule.required().min(60).max(400),
    }),
    defineField({
      name: "category",
      title: "分类",
      type: "string",
      group: "content",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "author",
      title: "作者",
      type: "string",
      initialValue: "AVIORA China Team",
      group: "content",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "readingTime",
      title: "阅读时间",
      type: "string",
      initialValue: "5 min read",
      group: "content",
    }),
    portableTextField,
    defineField({
      name: "heroImage",
      title: "Hero 图片",
      type: "r2Image",
      group: "media",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "gallery",
      title: "图片画廊",
      type: "array",
      of: [defineArrayMember({ type: "r2Image" })],
      group: "media",
    }),
    defineField({
      name: "tags",
      title: "标签",
      type: "array",
      of: [defineArrayMember({ type: "string" })],
      options: { layout: "tags" },
      group: "relations",
    }),
    defineField({
      name: "relatedDestinations",
      title: "关联目的地",
      type: "array",
      of: [defineArrayMember({ type: "reference", to: [{ type: "destination" }] })],
      group: "relations",
    }),
    defineField({
      name: "featured",
      title: "编辑精选",
      type: "boolean",
      initialValue: false,
      group: "relations",
    }),
    defineField({
      name: "publishedAt",
      title: "发布日期",
      type: "datetime",
      group: "relations",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "sortOrder",
      title: "排序",
      type: "number",
      initialValue: 100,
      group: "relations",
    }),
    ...seoFields,
  ],
  preview: { select: { title: "title", subtitle: "category" } },
});
