import { defineArrayMember, defineField, defineType } from "sanity";

const textBlock = defineArrayMember({
  type: "object",
  fields: [
    defineField({
      name: "title",
      title: "标题",
      type: "string",
      validation: (rule) => rule.required(),
    }),
    defineField({ name: "description", title: "说明", type: "text", rows: 3 }),
  ],
});

export const homePageType = defineType({
  name: "homePage",
  title: "首页设置",
  type: "document",
  groups: [
    { name: "hero", title: "Hero" },
    { name: "featured", title: "精选内容" },
    { name: "why", title: "品牌优势" },
    { name: "planning", title: "规划流程" },
    { name: "trade", title: "行业背书" },
    { name: "journal", title: "博客" },
    { name: "cta", title: "底部 CTA" },
  ],
  fields: [
    defineField({ name: "heroEyebrow", title: "Hero 品牌行", type: "string", group: "hero" }),
    defineField({
      name: "heroTitle",
      title: "Hero 主标题",
      type: "string",
      group: "hero",
      validation: (rule) => rule.required(),
    }),
    defineField({ name: "heroCopy", title: "Hero 说明", type: "text", rows: 3, group: "hero" }),
    defineField({
      name: "heroImage",
      title: "Hero 图片",
      type: "r2Image",
      group: "hero",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "heroTrustItems",
      title: "Hero 信任标签",
      type: "array",
      group: "hero",
      of: [defineArrayMember({ type: "string" })],
    }),
    defineField({
      name: "featuredJourneys",
      title: "精选行程",
      type: "array",
      group: "featured",
      of: [defineArrayMember({ type: "reference", to: [{ type: "journey" }] })],
      validation: (rule) => rule.max(6),
    }),
    defineField({
      name: "featuredDestinations",
      title: "精选目的地",
      type: "array",
      group: "featured",
      of: [defineArrayMember({ type: "reference", to: [{ type: "destination" }] })],
      validation: (rule) => rule.max(8),
    }),
    defineField({
      name: "featuredPosts",
      title: "精选文章",
      type: "array",
      group: "featured",
      of: [defineArrayMember({ type: "reference", to: [{ type: "blogPost" }] })],
      validation: (rule) => rule.max(4),
    }),
    defineField({
      name: "destinationsEyebrow",
      title: "目的地章节标签",
      type: "string",
      group: "featured",
    }),
    defineField({
      name: "destinationsTitle",
      title: "目的地章节标题",
      type: "string",
      group: "featured",
    }),
    defineField({
      name: "destinationsCopy",
      title: "目的地章节说明",
      type: "text",
      rows: 3,
      group: "featured",
    }),
    defineField({ name: "whyEyebrow", title: "Why AVIORA 标签", type: "string", group: "why" }),
    defineField({ name: "whyTitle", title: "Why AVIORA 标题", type: "string", group: "why" }),
    defineField({ name: "whyCopy", title: "Why AVIORA 说明", type: "text", rows: 3, group: "why" }),
    defineField({
      name: "whyStats",
      title: "Why AVIORA 数据项",
      type: "array",
      group: "why",
      of: [textBlock],
      validation: (rule) => rule.max(4),
    }),
    defineField({
      name: "whyPoints",
      title: "Why AVIORA 承诺",
      type: "array",
      group: "why",
      of: [textBlock],
      validation: (rule) => rule.max(4),
    }),
    defineField({
      name: "planningEyebrow",
      title: "规划章节标签",
      type: "string",
      group: "planning",
    }),
    defineField({
      name: "planningTitle",
      title: "规划章节标题",
      type: "string",
      group: "planning",
    }),
    defineField({
      name: "planningCopy",
      title: "规划章节说明",
      type: "text",
      rows: 3,
      group: "planning",
    }),
    defineField({
      name: "planningImage",
      title: "规划章节图片",
      type: "r2Image",
      group: "planning",
    }),
    defineField({
      name: "planningSteps",
      title: "规划步骤",
      type: "array",
      group: "planning",
      of: [textBlock],
      validation: (rule) => rule.max(5),
    }),
    defineField({ name: "tradeEyebrow", title: "行业背书标签", type: "string", group: "trade" }),
    defineField({ name: "tradeTitle", title: "行业背书标题", type: "string", group: "trade" }),
    defineField({
      name: "tradeCopy",
      title: "行业背书说明",
      type: "text",
      rows: 3,
      group: "trade",
    }),
    defineField({
      name: "tradeImages",
      title: "行业背书图片",
      type: "array",
      group: "trade",
      of: [defineArrayMember({ type: "r2Image" })],
      validation: (rule) => rule.max(3),
    }),
    defineField({
      name: "journalEyebrow",
      title: "博客章节标签",
      type: "string",
      group: "journal",
    }),
    defineField({ name: "journalTitle", title: "博客章节标题", type: "string", group: "journal" }),
    defineField({
      name: "journalCopy",
      title: "博客章节说明",
      type: "text",
      rows: 3,
      group: "journal",
    }),
    defineField({ name: "ctaEyebrow", title: "底部 CTA 标签", type: "string", group: "cta" }),
    defineField({ name: "ctaTitle", title: "底部 CTA 标题", type: "string", group: "cta" }),
    defineField({ name: "ctaCopy", title: "底部 CTA 说明", type: "text", rows: 3, group: "cta" }),
    defineField({ name: "ctaImage", title: "底部 CTA 图片", type: "r2Image", group: "cta" }),
  ],
  preview: { prepare: () => ({ title: "AVIORA 首页内容" }) },
});
