import { defineArrayMember, defineField, defineType } from "sanity";

import { commonGroups, seoFields } from "@/sanity/schemaTypes/shared";

export const journeyType = defineType({
  name: "journey",
  title: "行程",
  type: "document",
  groups: commonGroups,
  fields: [
    defineField({
      name: "title",
      title: "行程标题",
      type: "string",
      group: "content",
      validation: (rule) => rule.required().min(8).max(120),
    }),
    defineField({
      name: "slug",
      title: "URL Slug",
      type: "slug",
      options: { source: "title", maxLength: 96 },
      group: "content",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "subtitle",
      title: "副标题",
      type: "text",
      rows: 2,
      group: "content",
      validation: (rule) => rule.required().min(20).max(260),
    }),
    defineField({
      name: "summary",
      title: "列表摘要",
      type: "text",
      rows: 3,
      group: "content",
      validation: (rule) => rule.required().min(40).max(420),
    }),
    defineField({
      name: "route",
      title: "途经城市",
      type: "string",
      group: "content",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "durationLabel",
      title: "行程天数",
      type: "string",
      description: "例如 10-12 days",
      group: "content",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "price",
      title: "价格说明",
      type: "string",
      initialValue: "Price on request",
      group: "content",
    }),
    defineField({
      name: "bestFor",
      title: "适合人群",
      type: "string",
      group: "content",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "intro",
      title: "行程开场",
      type: "text",
      rows: 5,
      group: "content",
      validation: (rule) => rule.required().min(120),
    }),
    defineField({
      name: "days",
      title: "逐日行程",
      type: "array",
      group: "content",
      validation: (rule) => rule.required().min(3),
      of: [
        defineArrayMember({
          type: "object",
          name: "journeyDay",
          fields: [
            defineField({
              name: "day",
              title: "天数",
              type: "string",
              validation: (rule) => rule.required(),
            }),
            defineField({
              name: "city",
              title: "城市",
              type: "string",
              validation: (rule) => rule.required(),
            }),
            defineField({
              name: "title",
              title: "当天标题",
              type: "string",
              validation: (rule) => rule.required(),
            }),
            defineField({
              name: "description",
              title: "当天内容",
              type: "text",
              rows: 4,
              validation: (rule) => rule.required().min(30),
            }),
            defineField({ name: "image", title: "当天图片", type: "r2Image" }),
          ],
          preview: { select: { title: "title", subtitle: "day" } },
        }),
      ],
    }),
    defineField({
      name: "heroImage",
      title: "Hero 图片",
      type: "r2Image",
      group: "media",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "gallery",
      title: "图片画廊",
      type: "array",
      of: [defineArrayMember({ type: "r2Image" })],
      group: "media",
    }),
    defineField({
      name: "styles",
      title: "旅行风格",
      type: "array",
      of: [defineArrayMember({ type: "string" })],
      options: { layout: "tags" },
      group: "relations",
    }),
    defineField({
      name: "destinations",
      title: "目的地",
      type: "array",
      of: [defineArrayMember({ type: "reference", to: [{ type: "destination" }] })],
      group: "relations",
    }),
    defineField({
      name: "featured",
      title: "首页精选",
      type: "boolean",
      initialValue: false,
      group: "relations",
    }),
    defineField({
      name: "sortOrder",
      title: "排序",
      type: "number",
      initialValue: 100,
      group: "relations",
    }),
    ...seoFields,
  ],
  orderings: [
    { title: "手动排序", name: "sortOrder", by: [{ field: "sortOrder", direction: "asc" }] },
  ],
  preview: { select: { title: "title", subtitle: "durationLabel" } },
});
